### ISSUE TITLE
Add lowercase L for litres

### ISSUE THREAD

**Issue by ksrm** [sharkdp/insect#100]
This is the standard symbol for litres in Europe.

https://en.wikipedia.org/wiki/Litre#Symbol

**Comment by sharkdp** [comment]
I would really like to use lowercase `l` for `liter`, as I'm also used to reading it like this (e.g. `330 ml`).

The only drawback is that `l` is commonly used as an identifier for lengths. This change would prohibit users from using it ("Parse error .. 'l' is reserved for a physical unit"). This is also the reason I initially chose to only add uppercase `L`.

What do you think?

**Comment by ksrm** [comment]
I suppose you could say the same thing about `h` (often used for height, but reserved for hours) and 'd' (distance/depth, reserved for days), but I understand your reasoning. It's not too much of an inconvenience to have to use `L`.

**Comment by sharkdp** [comment]
No, good point. Let's add it.
