### ISSUE TITLE
Negative powers cause parse error

### ISSUE THREAD

**Issue by anowlcalledjosh** [sharkdp/insect#101]
Using a negative literal as a power causes a parse error:

```
>>> 4^-1

  Parse error at position 2: Expected end of input

>>> 4^(-1)

  4^(-1)

   = 0.25
```

Having to put parens around `-1` as a power is awkwardly verbose/unreadable, and using `per` often needs extra brackets when dividing (e.g. `78.5g / 170 g mol^(-1)` parses as `78.5 g / (170 g × mol^(-1))`, whereas `78.5g / 170 g per mol` parses as `(78.5 g / 170 g) / mol`).

**Comment by sharkdp** [comment]
That would be nice. Somehow when I was initially writing the Parser, I couldn't get this to work - so any help would be greatly appreciated.

**Comment by sharkdp** [comment]
I finally figured this out!

This is now supported:

![image](https://user-images.githubusercontent.com/4209276/29382938-8e78dbec-82ce-11e7-94fa-1dfada2cb193.png)


@anowlcalledjosh Would be great to hear if this works for you as expected. Thank you for reporting this.

**Comment by anowlcalledjosh** [comment]
Yep, works great! Thanks :)
