### ISSUE TITLE
Superscript minus cannot be parsed

### ISSUE THREAD

**Issue by anowlcalledjosh** [sharkdp/insect#102]
The rest of Insect's output seems to be parseable, it's a shame this isn't (even if I can't actually type the character...)

```
>>> avogadroConstant

  avogadroConstant

   = 6.02214e+23 mol⁻¹

>>> 6.02214e+23 mol⁻¹

  Parse error at position 16: Expected end of input
```

Thank you for making such an awesome app, by the way!

**Comment by sharkdp** [comment]
Yes, good catch. My intention was indeed that the output of the pretty printer is always parseable, so this needs to be fixed.

Thank you for the feedback.

**Comment by sharkdp** [comment]
This is fixed now:

```
>>> avogadroConstant

  avogadroConstant

   = 6.02214e+23 mol⁻¹

>>> 6.02214e+23 mol⁻¹

  6.02214e+23 × mol^(-1)

   = 6.02214e+23 mol⁻¹
```

Thanks for reporting!
