### ISSUE TITLE
Support more pressure units

### ISSUE THREAD

**Issue by leipert** [sharkdp/insect#103]
These are the pressure units I found on wikipedia:
- [x] Bar
- [x] Pascal
- [x] [mmHg](https://en.wikipedia.org/wiki/Millimeter_of_mercury)
- [x] [psi](https://en.wikipedia.org/wiki/Pounds_per_square_inch)
- [ ] [at](https://en.wikipedia.org/wiki/Technical_atmosphere)
- [x] [atm](https://en.wikipedia.org/wiki/Atmosphere_(unit))
- [ ] [Torr](https://en.wikipedia.org/wiki/Torr)

afaik at least mmHg (in medicine/meteorology) and psi (pressure on tires) are still used enough that it might warrant implementation

**Comment by sharkdp** [comment]
Good suggestion!

**Comment by sharkdp** [comment]
`mmHg`, `psi` and `atm` are now supported.
