### ISSUE TITLE
Web Text Result

### ISSUE THREAD

**Issue by amirarsalan** [sharkdp/insect#106]
Hey,
I have an idea. change web version that returns the result by a clear text.
`
$ curl https://insect.sh/sqrt(9)
`
return this result:
> 3

this can be useful!

**Comment by sharkdp** [comment]
Did you see that there is a terminal version? It can do something like this:
```
> insect 'sqrt(9)'
3
```
Of course, it's not the same as a webservice as it requires insect to be installed.

Insect-as-a-service is a neat idea, but currently insect.sh is only HTML+JavaScript. Your idea would probably require a node server to be running?

**Comment by amirarsalan** [comment]
Yes, We have a node server or something else.
I know you have a command line solution but this isn't fair enough!
I write the same code for this I can pull request this or can setup on my server. this solution can be so useful for me or my colleagues.

**Comment by sharkdp** [comment]
Closing this for now, as there does not seem to be any ongoing work and I don't really see a strong use case.
