### ISSUE TITLE
Add configuration command 

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#107]
Some things came up that a user might want to configure:
- number of significant digits that are displayed (default: 6)
- ~decimal separator: `.` vs `,`~
- terminal prompt
- pretty printing: on/off
- ...

I'd like to introduce a new keyword (e.g. `set`) that can control these:
```
> set displayed_digits 10
> set prompt "insect >>> "
```

Then, in a second step, we could read in a file like `~/.config/insectrc` during startup where these settings (and user-defined variables) could be stored. For the web-version, settings could be stored in `localStorage`.

**Comment by leipert** [comment]
IMO: we should keep the possible config parameters to a minimum.

**Comment by sharkdp** [comment]
Released in v5.7.0

**Comment by sharkdp** [comment]
Reopening for the `set` commands.

**Comment by sharkdp** [comment]
Follow-up ticket for Numbat: https://github.com/sharkdp/numbat/issues/97
