### ISSUE TITLE
Support for modulo

### ISSUE THREAD

**Issue by WoutervdBrink** [sharkdp/insect#114]
I would love support for modulo, as some of the formulas I'm working with require it. Unfortunately I know nothing about Purescript, so I wouldn't know how to implement it.

**Comment by sharkdp** [comment]
Thank you for the feedback!

How would the semantics of this operation look like? If we were to add a modulo operator `%`, what would `N % D` do exactly? Both `N` and `D` are expressions themselves and they evaluate to quantities which might (potentially) have physical units attached to them.

* Do we try to cast `D` to a scalar value (like if someone calls `sin(D)`) and keep the unit of `N` for the result?
* Do we try to cast `D` to the same unit as `N`?
* Do we have to cast both to scalar values?

Floating point numbers should not be a problem, as we would probably implement `fmod`.

**Comment by WoutervdBrink** [comment]
Thank you for the reply.

To be honest I have no idea, but I'll give it a try and maybe my feedback can help you. I'm not that good at math, and my knowledge of modulo goes no further than that x mod y "means" that we keep subtracting y from x, and return whatever we have left when we cannot subtract anymore.

I'd say that you only allow modulo on anything that is compatible. Doing "2 meter modulo 7 centimeter" makes sense whenever you're trying to find out how much room you've got left when you're stacking bricks of 7 cm high in a room that's 2m tall. However, doing "2 seconds modulo 5 cm" does not really make sense. We cannot subtract 5 centimeter from 2 seconds, making the behavior undefined.

I'd say that you only allow scalar or scalar-like values, and with physical units which are of the same kind, like length, volume, area or time.

**Comment by sharkdp** [comment]
Thanks, that sounds very reasonable. I'll look into it when I'm back home (in a few weeks).

**Comment by sharkdp** [comment]
Thank you very much again!

This is now supported:
```
≫ 19 % 12
  19 % 12
   = 7
≫ (-1) % 5
  (-1) % 5
   = 4
≫ 200cm % 7cm
  (200 cm) % (7 cm)
   = 4 cm
≫ 2m % 7cm
  (2 m) % (7 cm)
   = 0.04 m
≫ 2 seconds % 5 centimeter
  (2 s) % (5 cm)
  Conversion error:
    Cannot convert unit cm (base units: m)
                to unit s
```

Would be great to get your feedback if this works for you as expected.

**Comment by WoutervdBrink** [comment]
Exactly as I imagined it, thank you very much!

**Comment by sharkdp** [comment]
Great to hear that, thank you for the feedback.
