### ISSUE TITLE
Support for rods and hogsheads

### ISSUE THREAD

**Issue by karel1980** [sharkdp/insect#115]
Insert obligatory Simpsons reference

https://i.imgflip.com/1f94ti.jpg

https://www.google.be/search?client=ubuntu&channel=fs&q=rods+per+hogshead&ie=utf-8&oe=utf-8&gfe_rd=cr&ei=stBjWZbPB6eD3gOgh5fYCg

**Comment by sharkdp** [comment]
Thanks :smile: 

This is now supported:

```
≫ 40 rods/hogshead to mile/gal
   = 0.00198413 mi/gal

≫ 40 rods/hogshead to ft/gal
   = 10.4762 ft/gal
```

**Comment by karel1980** [comment]
Haha. Awesome! Great job
