### ISSUE TITLE
Add Support for Summation and Multiplication Notation

### ISSUE THREAD

**Issue by dyedgreen** [sharkdp/insect#116]
It would be cool to have commands to indicate summation and multiplication, maybe in the form of `sum n = 1 to 20 (n)` meaning 1 + 2 + 3 + 4 + 5 + ... + 20 and `product n = 1 to 20 (n + 7)` meaning (1 + 7) * (2 + 7) * ... * (20 + 7).

**Comment by sharkdp** [comment]
Thank you very much for your feedback!

This would be a completely new language feature, similar to loops in a programming language. I'm not *100%* sure, I want insect to go in this direction but if we can implement this in a clean way, :+1:.

I would definitely propose a different syntax, though. It took me quite some time to mentally parse `product n = 1 to 20 (n + 7)` to mean:

![\prod_{n=1}^{20} (n+7)](https://user-images.githubusercontent.com/4209276/28752408-8d724912-751e-11e7-8d62-f123aa3ceee4.gif)

I don't have any really good ideas... maybe `product(n+7, n, 1, 7)` in the style of Mathematicas `Product[n+7, {n, 1, 7}]`?


Note: we already have the factorial function/operator for simple products.

**Comment by dyedgreen** [comment]
Thanks for your response.

I guess a different syntax might me a good idea. I don't really know what kind of syntax would be best though. I think the function style syntax might work (`sum(n*5, n, 1, 10)`).

I fell this would be a rather useful feature though, since some calculations require sums/products that are very elaborate to write out manually.

**Comment by sharkdp** [comment]
This is now supported.

@dyedgreen Your feedback would be appreciated, thank you for the idea!

Examples:
```
>>> sum(n, n, 1, 20)

  sum(n, n, 1, 20)

   = 210

>>> product(n + 7, n, 1, 20)

  product(n + 7, n, 1, 20)

   = 2.16049e+24

>>> myFactorial(n) = product(k, k, 1, n)

  myFactorial(n) = product(k, k, 1, n)

>>> myFactorial(10)

  myFactorial(10)

   = 3628800

>>> sum(k^2, k, 1, 10)

  sum(k^2, k, 1, 10)

   = 385
```

**Comment by dyedgreen** [comment]
This is exactly what I've been missing. Thank you for implementing this feature!
