### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by Fnux** [sharkdp/insect#117]
I built a rpm package for insect : https://copr.fedorainfracloud.org/coprs/fnux/insect/
Feel free to add it to the README if you want to.

**Comment by sharkdp** [comment]
Very cool, thank you very much!

I'm not a Fedora user. Would it be correct to add a paragraph like this:

---

For Fedora, there is a [RPM package](https://copr.fedorainfracloud.org/coprs/fnux/insect/):

```
sudo dnf copr enable fnux/insect
sudo dnf install insect
```

**Comment by Fnux** [comment]
A 'copr repository' would be better.

**Comment by sharkdp** [comment]
Okay, thanks. Like this?

**Comment by Fnux** [comment]
Yes :)
