### ISSUE TITLE
man page

### ISSUE THREAD

**Issue by Fnux** [sharkdp/insect#118]
Would it be possible to have a man page for `insect` ? It's always a good thing to have one :)

**Comment by sharkdp** [comment]
Good idea!

I would really like to avoid duplication of documentation in different places, though. Right now, the most comprehensive documentation is in the `README.md` file.

Maybe there is a way to auto-create both the README.md and the man page from a single documentation source file (also in markdown?). Pandoc might be a good option. It produces a rather neat document from the current README, actually:
``` bash
pandoc -f markdown -t man README.md --standalone -V title=insect | man -l -
```

**Comment by Fnux** [comment]
`pandoc` works fine but we don't want everything in the man page (we don't care about the installation instructions). The 'easy' way would be to use a documentation file separated from`README.md`.

**Comment by sharkdp** [comment]
I've split up the documentation such that the man page can now be auto-generated from the markdown input (+ header / footer). Could you please check if this works for you (install v4.9.1 via npm and call `man insect`)? Thanks!

**Comment by Fnux** [comment]
I don't use npm, but successfully packaged the latest version (v5.0.0, including the manpage) for fedora.
You should update the `help` message to mention the manpage.
