### ISSUE TITLE
Math-Error for rational exponents with negative base

### ISSUE THREAD

**Issue by dyedgreen** [sharkdp/insect#123]
When given a negative base, rational exponents don't seem to work properly. For example the third root of -27 gives this instead of -3:
```
>>> (-27)**(1/3)

  (-27)^(1 / 3)

  Numerical error: division by zero or out-of-bounds error
```

**Comment by sharkdp** [comment]
This is fundamentally connected to the question whether Insect has support for complex numbers (#47).

There are three complex 3rd roots of `-27` (and correct answers to `(-27)^(1/3)`):
```
z_1 = 3 exp(iπ / 3)
z_2 = 3 exp(iπ) = -3
z_3 = 3 exp(-iπ / 3)
```
Typically, calculators with support for complex numbers make an explicit choice which answer they give.
 For example: the one with the smallest angle in the polar representation, or: one of the real answers (if there are any).

In your particular case, there happens to be a real-valued solution to `x^y` for `x` negative and `y` non-integer: `z_2 = -3`. However, this need not be the case. If you had asked for `(-27)^0.33`, there would not be a real-valued answer.

Even if there would be support for complex numbers, there is a problem: Insect is a numerical calculator and represents numbers in a (high-precision) floating point format. This means, that there is no precise representation of the fraction `1/3`.

**Comment by sharkdp** [comment]
@dyedgreen Any feedback on this?

**Comment by dyedgreen** [comment]
Sorry for the late reply.
I think that given Insect supports real-numbers only, it would be logical to try to find the real-valued answer only. However given that Insect is a numerical calculator, I understand that non integer powers can be tricky to deal with and run into rounding errors like the one above.

**Comment by sharkdp** [comment]
Thanks!
