### ISSUE TITLE
Persistent user sessions

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#124]
Use cases:
- A user often works with a certain set of variables/functions and wants to store them between sessions (and load them by default).
- A user works on two different projects and uses different environments in each of them..
- A user does not like the default variable names and wants to redefine some of them.

Possible design:
* Add `save` and `load` commands. Both take an optional string argument (session name)
* `save foo` saves the current session (all variables and user-defined functions); `load foo` restores that session (on top of the current environment?).
* If no name is given, `save` stores the current session under a default name. On startup, this default session is re-loaded. Similarly, `load` retrieves the last-`save`d session.

**Comment by erlenstar** [comment]
++. I was about to file a suggestion to give insect a .rc file, but I like the persistent sessions idea even better!

**Comment by mhmdanas** [comment]
I do think this is a nice idea, but for what it's worth the first and third use cases are satisfied by the `.insectrc` file added recently.

**Comment by sharkdp** [comment]
I think this is now reasonable solved with Numbats customizations features: https://numbat.dev/doc/cli-customization.html
