### ISSUE TITLE
Pretty-printer: use long name for units and prefixes

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#126]
```
≫ 5 d + 2 h

  5 day + 2 hour

   = 5.08333 d
```

**Comment by mhmdanas** [comment]
I guess this would solve https://github.com/sharkdp/insect/issues/151 if implemented, wouldn't it?

**Comment by sharkdp** [comment]
No, I think this is unrelated. This is not about parsing at all. I think the idea was just to show `5.08333 day` instead of `… d`.

**Comment by sharkdp** [comment]
But I'm not sure this whole ticket such a good idea. What about something like `km/h`. I don't think we want that expanded to "kilometer/hour"

**Comment by mhmdanas** [comment]
> No, I think this is unrelated. This is not about parsing at all. I think the idea was just to show 5.08333 day instead of … d.

Well, if `mile` is shown as `mile` instead of `mi`, that would solve the issue, would it not?

> But I'm not sure this whole ticket such a good idea. What about something like km/h. I don't think we want that expanded to "kilometer/hour"

Yeah, expanding everything is not a good idea in my opinion too.

**Comment by sharkdp** [comment]
> Well, if `mile` is shown as `mile` instead of `mi`, that would solve the issue, would it not?

it would solve the inconsistency between output and input, right. It would not solve the problem that some people apparently want to use "mi" for "mile".

But yeah, I'd be perfectly fine with changing that "mi" short version to "mile" to resolve that inconsistency.

**Comment by sharkdp** [comment]
This is now resolved in Numbat: https://numbat.dev/?q=5+d+%2B+2+h
