### ISSUE TITLE
Insect v5.0.0 is now supported in Judge0 API

### ISSUE THREAD

**Issue by hermanzdosilovic** [sharkdp/insect#130]
Hello,

I am creator of [Judge0](https://judge0.com) and I just wanted to let you know that Insect is now supported in [Judge0 API](https://api.judge0.com) and can be used online on [Judge0 IDE](https://ide.judge0.com). :smile: 

BR,
Herman

**Comment by sharkdp** [comment]
Very nice!! Thank you very much.

I think this is similar to what @amirarsalan was looking for in #106.
