### ISSUE TITLE
Possible to separate namespace of units vs. of user-defined variables?

### ISSUE THREAD

**Issue by desmond-dsouza** [sharkdp/insect#133]
The flow would be less interrupted (i.e. even more awesome) if I did not have to retype (and re-think) each time I used, say, "m" as a variable name.

But this would probably require syntax changes e.g. implicit multiplication to disambiguate "20 m" between 

> 20 meters

 and 

> 20 * variable("m")

**Comment by sharkdp** [comment]
That would be nice. Unfortunately, I don't know how to resolve this without introducing any ambiguities. We could always try to interpret `m` as `variable("m")` first, if it exists, but I would really like to avoid the possibility of users overwriting units by accident.

One thing that has been suggested in the past is to allow variables to begin with a special character (say `$`). This way, you could always name your variables without thinking (at the cost of having to type an additional character). The only reason I haven't added this is that is looks weird to me :smile:
```
$l * cos($phi)
```

**Comment by sharkdp** [comment]
@desmond-dsouza What do you think?

**Comment by sharkdp** [comment]
Thank you for the suggestion.

> 27 * m kg * m / s^2
> 
> That might make it unambiguous that the first m is a variable, and the second m is the unit meter.

It might be just me, but this expression is an example why I would like to keep disallowing name clashes. It's not at all obvious to me that the first `m` is a variable. In fact I would guess that it would be interpreted as `27 * meter kg * meter / second^2` by most people who would not be aware about special implicit/explicit syntax rules.

I am trying to design the syntax and the error messages of Insect in a way that helps users from shooting themselves in the foot. A user who would be unaware of such syntax rules might create a new variable `l` without realizing that there is a unit with the same name (`liter`). If he then proceeds to use the term `l` in the wrong way, he would end up with a very confusing error message.

Sure, syntax highlighting in the pretty-printer output helps - but you would have to be aware that you are potentially doing something ambiguous.

I would very much like to have a solution for this issue - but I'm afraid this approach would have too many downsides.


> I agree that $phi looks a bit weird.

Other possibilities are (these already work): `_phi`, `phi_`, `phi'`. What I'm usually doing is writing full words (or abbreviations) for the variable names:
* `l` -> `len`, `length`
* `m` -> `mass`
* `g` -> `gravity`
* ..

**Comment by desmond-dsouza** [comment]
Valid points, but think finding a workable syntax to allow free choice of variable names (modulo built-in constants, perhaps) would be really nice, so I won't give up 😄 

What if every top-level unit-expression (not its subexpressions) had to be put into square brackets? 

```
m = 23 [kg]
f = m *  13.2 [m/s^2]  / 13 [ft]
```

There is some precedent since `[expr]` is used to mean *the units of `expr`*.

Btw, are you comfortable with showing the value of `kg` to be `1 kg`? Something there feels wrong to me, but have not tried to look at the implementation. 
![image](https://user-images.githubusercontent.com/4407158/32687422-46eef9c2-c681-11e7-9db9-9383655bf9cd.png)

**Comment by sharkdp** [comment]
> Valid points, but I think finding a workable syntax to allow free choice of variable names (modulo built-in constants, perhaps) would be really nice, so I won't give up

:+1: 

> What if every top-level unit-expression (not its subexpressions) had to be put into square brackets?
> ```
> m = 23 [kg]
> f = m *  13.2 [m/s^2]  / 13 [ft]
> ```
> There is some precedent since `[expr]` is often used to mean the units or dimensions of `expr`.

I'm definitely against this. Many programming languages / calculators let you define your own variable names, but the special thing about Insect is that physical units are "first-class citizens" with a straight-forward syntax. Having to type `[` and `]` every time I want to use a physical unit would be a huge drawback for me.

So here is another idea (that I haven't completely thought through):

What if we allow for overriding of unit names (`m = 2`), but show a message to the user:

*"Warning: The definition of 'm' overwrites the physical unit 'meter', which will not be accessible anymore. To undo this, type 'reset m'."*

---

> Btw, are you comfortable with showing the value of kg to be 1 kg?

Absolutely. I agree that `kg` on its own looks strange, but physical units are mathematical expressions that can be handled just like scalars or variables. For each of these, we have `1 * X = X`.

If you are interested in the implementation, the fact that they are on an equal footing is represented by this sum type:

https://github.com/sharkdp/insect/blob/4656d7a98cd6d3ad9b0f0cc5fb8c3e71e0c98f12/src/Insect/Language.purs#L47-L55

**Comment by desmond-dsouza** [comment]
Ah, had not realized I could write `22 m / s^(log(3))` !  So effectively a single namespace by design?

I don't think overriding is a good option. Would `Expression` as a GADT help any by prying things apart in type-space?

**Comment by sharkdp** [comment]
> So effectively a single namespace by design?

The `Expression` type is not related to the namespace issue. This was just to show that `Scalar`, `Unit`, and `Variable` can all be used everywhere where an `Expression` is needed.

> I don't think overriding is a good option.

Yeah, okay.

> Would Expression as a GADT help any by prying things apart in type-space?

I don't see how that would make anything better per-se, to be honest.

**Comment by desmond-dsouza** [comment]
Having played with it some more, I better understand the flexibility you have designed in.

What if we modified your override-but-warn approach to always have qualified names available for all built-ins, something like this:

"Warning: The definition of `m` overwrites the built-in short name for the physical unit `meter`, which is now only accessible by its full name `meter`, or qualified short name `u:m`. To undo this, type `reset m`."

Perhaps the same approach could be used for built-in constants as well.

**Comment by sharkdp** [comment]
I'm going to close this for now because (1) I don't think its too much of a problem to add a prefix/postfix to variable names that clash with physical units and (2) I don't really like any of the alternatives we came up with.

Feel free to comment here if you think this should be reopened.
