### ISSUE TITLE
Add support for rational numbers

### ISSUE THREAD

**Issue by adius** [sharkdp/insect#139]
I was expecting something like with Haskell's Ratio module was possible:

```haskell
Prelude> import Data.Ratio
Prelude Data.Ratio> 85 % 55
17 % 11
```

**Comment by sharkdp** [comment]
Thank you for your feedback.

At a first glance, this looks like something that would be nice to have - I agree.

However, this would require some rather fundamental changes to large parts of the code base - and probably also the (command-line) user interface. We would basically have to introduce a kind of type system that kept track of whether certain expressions are supposed to be floating point numbers or integers/rationals. Also, we would have to introduce functions/syntax to convert between the two (sometimes you want the answer to 85/55 as a floating point number).

I guess this also addresses a rather basic design decision: do we want to support CAS-like features in Insect? For now, this is not the goal. Insect was really intended to be a "*high precision scientific calculator* with full support for physical units" - and nothing more. Everything is based on a (high-precision) floating point numeric type.

So in the spirit of "do one thing and do it well" I believe I would like to keep things simple - unless there is a really strong support / motivation for this. For now, I don't see too many use cases for rationals in a scientific calculator, to be honest.

**Comment by adius** [comment]
Ok, I see your point. I guess one use case - in the spirit of the program you just described - would still be to evaluate expressions lazily and try to simplify them before calcluting the final result to avoid rounding errors. But this sounds like a lot of work, too...

**Comment by sharkdp** [comment]
Yes, completely agreed. It would be great to be able to evaluate something like `sin(3pi/8+pi/8)` to *exactly* `1` but unfortunately I also think that this would be pretty limited unless we would go "full-blown" CAS.

I think this is the kind of thing one could re-evaluate if there will ever be a complete rewrite of the existing code base.

I'm going to close this for now but thank you very much for your feedback.

**Comment by adius** [comment]
I guess this was a bad example 😅:

```sh
$ insect 'sin(3pi/8+pi/8)'
1
```
😉
