### ISSUE TITLE
Support for pound-force

### ISSUE THREAD

**Issue by stifflerus** [sharkdp/insect#140]
The supported unit of pounds has dimension of mass. There should also be a unit pounds with dimension of force. This is important if you want to enter torque in imperial units (`lbf * ft`).  See [here](https://en.wikipedia.org/wiki/Pound_%28force%29).

The usual abbreviation for pound force is `lbf`. `Pounds` and `pound` are ambiguous between the two.

**Comment by sharkdp** [comment]
Thank you for the suggestion!

**Comment by stifflerus** [comment]
I would be happy to go ahead and implement this

**Comment by sharkdp** [comment]
Sounds great!

You would have to send a PR for [purescript-quantities](https://github.com/sharkdp/purescript-quantities) first.

**Comment by sharkdp** [comment]
I went ahead and implemented this, as I was making some changes to purescript-quantities anyways.

@stifflerus Would be great if you could verify that this works as expected

**Comment by stifflerus** [comment]
Works great!
