### ISSUE TITLE
Official Fedora package

### ISSUE THREAD

**Issue by Fnux** [sharkdp/insect#141]
Hello,

insect is on its way to Fedora's official repository! The [submission](https://bugzilla.redhat.com/show_bug.cgi?id=1538076) has been approved, I'm currently waiting for the [packaging of amissing dependency](https://bugzilla.redhat.com/show_bug.cgi?id=1433798).

**Comment by sharkdp** [comment]
Fantastic! :100: 

Thank you very much! Let me know when we should change the install instructions in the README.

**Comment by Fnux** [comment]
**Quick update:** the package is already built in Fedora rawhide [0] (development branch of Fedora) and will join F28 (the next release of Fedora [1]) in a few days.

[0] https://apps.fedoraproject.org/packages/insect
[1] https://fedoraproject.org/wiki/Releases/28/Schedule

**Comment by sharkdp** [comment]
:+1: :+1: :+1:

**Comment by Fnux** [comment]
Fedora 28 has been released yesterday and includes insect in the official repository. Can you update the README ? The copr repository is still available for Fedora 26 and 27.

**Comment by sharkdp** [comment]
> Fedora 28 has been released yesterday and includes insect in the official repository

:fireworks: 

> Can you update the README

Updated. Thanks again!
