### ISSUE TITLE
"per" should have higher precedence than / 

### ISSUE THREAD

**Issue by mdejean** [sharkdp/insect#143]
≫ 3 USD per gallon / 10 miles per gallon * 500 miles  
   (((3 USD / gal) / 10 mi) / gal) × 500 mi  
   = 150 USD/gal²

1 / mile per gallon is interpeted as (1/mile) per gallon. Much like implicit multiplication, "per" should have higher precedence than explicit division.

**Comment by sharkdp** [comment]
Thank you for the suggestion.

It seems to be sensible, given your example. But I'm curious ... is there any precedent for this (no pun intended) in other programs/contexts?

**Comment by mdejean** [comment]
https://www.google.com/search?q=100+miles+%2F+10+miles+per+gallon

**Comment by sharkdp** [comment]
Fixed:

```
≫ 3 USD per gallon / 10 miles per gallon * 500 miles
  ((3 USD / gal) / (10 mi / gal)) × 500 mi
   = 150 USD
```
