### ISSUE TITLE
When numbers are approximated, the ≈ symbol should be used.

### ISSUE THREAD

**Issue by lauritzt** [sharkdp/insect#144]
When results are approximated, the *almost equal to* symbol should be used.

Perhaps the symbol should be a different colour to draw attention to it.

**Expected:**

    1 / 9
     ≈ 0.111111

**Current:**

    1 / 9
     = 0.111111

**Comment by sharkdp** [comment]
Thank you for the feedback!

Insect is - fundamentally - a numerical calculator and not a CAS (see [Pros and cons](https://github.com/sharkdp/insect#pros-and-cons)). Unfortunately, it doesn't have any notion of 'exact'. Every computation is performed on (high-precision) floating point numbers.

So I guess the only option would be to display `≈` for *every* result. While technically correct, I think I would prefer to keep the `=` in this case.

What do you think?

**Comment by lauritzt** [comment]
Couldn't you test if the displayed result (`0.111111`) is equal to the more precise result stored internally? For example:

- 3.14159 is not equal to 3.14159265358979323846264338327, so display ≈.

- 0.26391 is equal to 0.26391000000000000000000000000, so display =.

**Comment by sharkdp** [comment]
Imagine a calculation like `1 / 3 * 6`. Insect currently says that the answer `= 2`. However, the internal representation of the result might very well be something like `0.9999…9`. With your proposal, it would probably say `≈ 2`.

**Comment by sharkdp** [comment]
Using an *absolute* threshold does not work. It's perfectly legal to work with numbers below that threshold:
```
>>> 3e-50 + 4e-50

  3e-50 + 4e-50

   = 7e-50
```


It *could* work with a *relative* threshold (compare `|display-exact|/|exact|` to a small threshold value). However, given that `exactResult` will never be the mathematically exact result (but a numerical result), I think that there will always be edge cases where this would be problematic.

**Comment by sharkdp** [comment]
Closing this as there is no further feedback.
