### ISSUE TITLE
Add support for multiline pasting in the web version

### ISSUE THREAD

**Issue by pzmarzly** [sharkdp/insect#145]
Current behavior is that the CLI version evaluates every line separately while pasting (so Return key only confirms the last command, but that matches the behavior of every CLI I've worked with), while web version treats all newline characters (`\n`) as whitespace, merging all commands into one (usually resulting in error).

![Screenshot](https://i.imgur.com/4USEYHc.png)

**Comment by sharkdp** [comment]
That would be great. I'm not sure if this is supported by [jquery.terminal](https://github.com/jcubic/jquery.terminal), though.

**Comment by pzmarzly** [comment]
I can see 2 solutions:

- to mimic shell behavior using `onCommandChange(command, terminal)` callback - see whether there are newline characters in command, if so, split the command and utilize `terminal.exec(commandLine, false)` and `terminal.set_command(commandLastLine)` - see [reference](https://terminal.jcubic.pl/api_reference.php)
- to simply parse the `\n` character and execute multiple commands at once - jquery.terminal doesn't remove newline character from entered commands

**Comment by sharkdp** [comment]
Thanks for looking into this!

I will take a look if I find some time. Any help would be greatly appreciated.

**Comment by n4bb12** [comment]
This could be a possible solution.
Basically this wraps `interpret` and the old `interpret` is renamed to `interpretLine`.

It is important that that the current line is returned back to the JQuery terminal as the next result, so any further lines need to be delayed (using `setTimeout`).

If you like the idea, I can make some improvements to it and create a PR.

```js
function interpret(input) {
  var lines = (input || "")
    .replace(/[\n\r]+/g, "\n")
    .split("\n");

  var result = interpretLine(lines[0]);

  if (lines.length > 1) {
    setTimeout(function() {
      term.exec(lines.slice(1).join("\n"));
    })
  }

  return result;
}
```

Output:
![2018-09-03 22_47_50-insect - scientific calculator](https://user-images.githubusercontent.com/6810177/45001199-6c992d80-afcb-11e8-9308-e4b442006d5e.png)

**Comment by n4bb12** [comment]
Yea the duplicates are undesirable. That was just an example to show that it's possible. If you want the feature I'll spend more time on it. Up to you 👍

**Comment by sharkdp** [comment]
I'd love to have that feature. Any help would be greatly appreciated!

**Comment by sharkdp** [comment]
This is now possible in the follow-up project: go to https://numbat.dev and try pasting
```
let len = 20 cm
2 pi sqrt(len/g0) -> ms
```

We can even share that as a link: https://numbat.dev/?q=let+len+%3D+20+cm%0A2+pi+sqrt%28len%2Fg0%29+-%3E+ms
