### ISSUE TITLE
Add command for searching

### ISSUE THREAD

**Issue by pzmarzly** [sharkdp/insect#146]
For some reason `Ctrl-R` combination doesn't work for me in CLI (probably some conflicting shortcut). Could you add a command that will trigger the search box? (There is a possibility such command exists already but I've missed it - consider mentioning it next to `Ctrl-R` in README then).

**Comment by sharkdp** [comment]
Unfortunately, `Ctrl-R` is not supported in the CLI version. If there is any node library that supports this (plus every feature that we use right now), I'd love to know.

**Comment by sharkdp** [comment]
I'm closing this for now, since I don't see any viable solution.
