### ISSUE TITLE
Add percentage symbol (%) calculation

### ISSUE THREAD

**Issue by megadr01d** [sharkdp/insect#147]
As in most UI calculators I've used and, most notably, in [libqalculate](https://github.com/Qalculate/libqalculate), it's possible to calculate a percentage the easy way, like `2000*25%` instead of having to enter `2000*25/100`.
Would love to see this implemented in `insect`.

**Comment by sharkdp** [comment]
The `%` operator is currently used for the modulo operation:
```
>>> 15 % 4

  15 % 4

   = 3
```

If we really need the percentage-symbol, we would have to remove the modulo operator (and replace it by `mod` or similar).

Another solution could be to define `percent = 0.01`, which would at least allow users to write `2000 * 25 percent`. This approach already works if you define it yourself:
```
>>> percent = 1/100

  percent = 0.01

>>> 2000*25percent

  2000 × 25 × percent

   = 500
```

**Comment by megadr01d** [comment]
Thanks a lot @sharkdp, didn't know about user definitions. That will do, no need to change the modulo operator based on a single request.
Closing and cheers!

**Comment by sharkdp** [comment]
Alright, thanks!

**Comment by sergeevabc** [comment]
90+10% = …

Common sense: 99 (since 1% = 90/100 = 0,9 so 10% = 0.9*10 = 9 so 90+9=99)
Numbat: 90.1

**Comment by sharkdp** [comment]
@sergeevabc Please see https://github.com/sharkdp/insect/issues/192. If you think this is something worth discussing, please open a ticket in the Numbat repository.

**Comment by sergeevabc** [comment]
@sharkdp, I wrote here so that you could explain what logic you follow when calculating percentages. At school they say one thing, but you say something else.

**Comment by sharkdp** [comment]
In Numbat, `%`/`percent` is simply a unit that equals 0.01. It behaves like a normal number. There is no special handling. You can still use it to compute "XY% *of* something" by multiplying `XY% × something`:

![image](https://github.com/sharkdp/insect/assets/4209276/43dae8d6-2791-4a06-8a42-78c87ad6b4ff)

But if you want to use it to compute "something *plus* XY % (of that something)", then you need to do `something + XY% something` or `something (1+XY%)`.

![image](https://github.com/sharkdp/insect/assets/4209276/5037e37f-b8da-481e-95a4-7d2ee13b3887)
