### ISSUE TITLE
Inconsistant unit conversions in web-ui version

### ISSUE THREAD

**Issue by Mrfiregem** [sharkdp/insect#148]
I may be inputting something wrong, but why does the second example equation convert correctly while the first does not?

> ≫ amp = 15 A
  amp = 15 A
≫ vol = 120 V
  vol = 120 V
≫ Pow = amp vol
  Pow = 1800 A·V
≫ ans to W
  ans ➞ W
  Conversion error:
    Cannot convert unit A
                to unit W (base units: kg·m²·s⁻³)

> ≫ pow = (120 V * 15 A) -> W
  pow = 1800 W

**Comment by sharkdp** [comment]
Thank you for your feedback.


Please note that `ans` will not be set if you define a variable. In your example, `ans` is not the same as `Pow` (it probably pointed to a previous result). If you change it to `Pow`, everything works as expected:

```
≫ amp = 15 A
  amp = 15 A
≫ vol = 120 V
  vol = 120 V
≫ Pow = amp vol
  Pow = 1800 A·V
≫ Pow to W
  Pow ➞ W
   = 1800 W
```

**Comment by Mrfiregem** [comment]
Oh, I assumed and would refer to the last solved variable, but that doesn't really make sense. Thanks for the clarification
