### ISSUE TITLE
Force exponential notation

### ISSUE THREAD

**Issue by cherkasovn** [sharkdp/insect#155]
Hi!
Thanks a lot for Insect - it is a really a great tool!
I wonder if I can force exponential notation onto the output? 
If I convert, say,  mm/min->m/s, I get the output with many zeros like 0.000017 m/s
However, I often want to get an exponential notation of the answer. The walkaround is obvious, but can I force the exponential notation?

**Comment by sharkdp** [comment]
Thank you very much for your feedback!

This is not possible, currently. I think it could be done once we implement #107.

**Comment by Tokarak** [comment]
How do I get an answer in exponential notation?
