### ISSUE TITLE
Can't convert to or from Volt

### ISSUE THREAD

**Issue by r0uv3n** [sharkdp/insect#156]
V -> N/(m^3\*C)  doesn't work, nor does N/(m^3\*C) -> V. insect displays the same base units for both.
Edit: fixed multiplication

**Comment by sharkdp** [comment]
Please take a close look at the error message that Insect gives, in particular the exponent for `meter`:

```
  Conversion error:
    Cannot convert unit V (base units: A⁻¹·kg·m²·s⁻³)
                to unit N/(m³·C) (base units: A⁻¹·kg·m⁻²·s⁻³)
```

A possible conversion involving these units would be:

```
V -> N·m/C
```
