### ISSUE TITLE
Add the ideal gas constant?

### ISSUE THREAD

**Issue by neilc314** [sharkdp/insect#158]
I find myself using insect a lot in thermodynamics, and it would be nice if it had the ideal gas constant.

    R = 8.3145 J/mol K

**Comment by sharkdp** [comment]
Thank you for the feedback!

The ideal gas constant sounds like a great addition. Let's add it.

In the meanwhile, you can type
```
R = k_B N_A
```

**Comment by sharkdp** [comment]
Fixed via #176 by @anilanar
