### ISSUE TITLE
How to set precision?

### ISSUE THREAD

**Issue by username1565** [sharkdp/insect#163]
Here https://username1565.github.io/insect/web/
You can enter this:
```5.4564 kWh -> kcal```
then terminal return this: ```= 4694.8 kcal```
but here https://www.google.com/search?q=5.4564+kwh+to+kcal
you can see the value 4694.79924 kcal !== 4694.8 kcal.

How to set precision?

**Comment by username1565** [comment]
Also not working peta- atto- femto- pico- with english units.
For example... 
`1 petawatt` -> `= 1 PW`
`1 oz` -> '1 oz'
`1 petaoz` -> `Unknown identifier: petaoz`
`1 femtofarad` -> `1 fF`
`1 femtocup` -> `Unknown identifier: femtocup`
`8 attoJ`->`8 aJ`
`8 attopound` -> `Unknown identifier: attopound`

Can anyone fix this?

**Comment by sharkdp** [comment]
Thank you for the feedback.

Please see #54 and #107.
