### ISSUE TITLE
Programmatic API

### ISSUE THREAD

**Issue by nikersify** [sharkdp/insect#164]
Hey, thanks for making insect, it's very useful!

The web and terminal ways that insect accepts input are great, however, since in theory insect is compiled to Javascript perhaps we could export an API for evaluating expressions with node.js scripts? 

I'm thinking of something akin to this:
```javascript
const insect = require('insect')

insect.eval('5 lightyears to parsecs') // `1.53301 parsec`
```

I've already tried do this via child processes - spawning one takes too much time for certain use cases and it would obviously be way more efficient to just have an exported method for this.

Thanks! 😄

**Comment by sharkdp** [comment]
Thank you for the feedback!

You can already do this, although the API is a little special because is PureScript-generated JavaScript. We could potentially build a nicer "JavaScript-like" wrapper around this:

``` javascript
▶ node
> const Insect = require('./output/Insect/index.js');
> const result = Insect.repl(Insect.fmtPlain)(Insect.initialEnvironment)("5 lightyears to parsecs");
> result.msg
'1.53301 parsec'
```

Have a look at "index.js", which is a node.js-application that uses the Insect API.

**Comment by sharkdp** [comment]
@nikersify I'm going to close this, as I feel that we already have a decent solution.
