### ISSUE TITLE
atto- femto- pico- peta- not working with english units. Need to fix this.

### ISSUE THREAD

**Issue by username1565** [sharkdp/insect#165]
not working peta- atto- femto- pico- with english units.
For example...
(OK) `1 petawatt` -> `1 PW`
(OK) `1 oz` -> `1 oz`
(FAIL) `1 petaoz` -> `Unknown identifier: petaoz`
(OK) `1 femtofarad -> `1 fF`
(FAIL) `1 femtocup` -> `Unknown identifier: femtocup`
(OK) `8 attoJ` -> `8 aJ`
(FAIL) `8 attopound` -> `Unknown identifier: attopound`

Can anyone fix this?
I see three variables in insect.js:
`V=new D([` - peta- atto- femto- giga-...
`da=new D([` - physics units
and
`P=new D([` - еnglish units.

Maybe, need to connect variable V to variable P.

**Comment by sharkdp** [comment]
This is on purpose.

SI-prefixes or metric prefixes are [typically not used with US-customary or imperial units](https://en.wikipedia.org/wiki/Metric_prefix#Non-metric_units). I don't have any intention of changing the current behavior and support something like "petaoz".
