### ISSUE TITLE
Need to fix double repeat symbol after copy and paste command

### ISSUE THREAD

**Issue by username1565** [sharkdp/insect#166]
1. Go to https://insect.sh/
2. Copy and paste something here.
3. press any key, and you will see doubling of symbol by this key.

**Comment by username1565** [comment]
I see an error in jquery.terminal-1.9.0.min.js so I fixed this using another way.
https://github.com/sharkdp/insect/pull/167

**Comment by sharkdp** [comment]
Thank you for the feedback. What do you mean by "double repeat symbol after copy and paste"?

**Comment by username1565** [comment]
@sharkdp,
1. Copy this command: `1 teraJ to kcal`
2. Go to https://insect.sh/
3. Paste this here.
4. press any key with letter after paste.
This letter is doubled there.

**Comment by sharkdp** [comment]
@username1565 Thank you.

**Comment by sharkdp** [comment]
Should be fixed in the latest online version.
