### ISSUE TITLE
BigInteger and BigRational support for web-version

### ISSUE THREAD

**Issue by username1565** [sharkdp/insect#168]
Hello. Can you add BigInteger and Bigrational support to web-version, on JavaScript.
I have this libraries and you can see this in my profile: https://github.com/username1565?tab=repositories

As you can see here: https://username1565.github.io/insect/web/?q=987654321987654321987654321987.1234567890987654321%20%D0%BA%D0%B8%D0%BB%D0%BE%D0%B2%D0%B0%D1%82%D1%82*%D1%87%D0%B0%D1%81%D0%BE%D0%B2%20to%20ExaJoules
big numbers not interpreted fully, as the float part of number.
So this was been rounded:
`3555560000000000000 EJ`

**Comment by sharkdp** [comment]
Not really sure what you are asking for here, please see my comments here: #167.

**Comment by username1565** [comment]
I mean supporting BigIntegers - long decimal integers,
like `123456789012345678901234567890123456789012345678901234567890`
because this rounded there:
`123456789012345678901234567890123456789012345678901234567890
  1.2345678901234567890123456789012345678901234567890123456789e+59
   = 1.23457e+59`
and supporting bigRatonal - long rational numbers, like
`1234567890123456789012345678901234567890.1234567890123456789012345678901234567890`
because this also rounded there:
`
≫ 1234567890123456789012345678901234567890.1234567890123456789012345678901234567890
  1.234567890123456789012345678901234567890123456789012345678901234567890123456789e+39
   = 1.23457e+39
`
So you can including BigInt_BigRat.min.js to web-version: https://github.com/peterolson/BigRational.js
and open the way for users to set precission, like there:
`bigRat(1,3).toDecimal(100) ===
"0.3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333"`
`bigRat(1,3).multiply("1e50").toDecimal(60) ===
"33333333333333333333333333333333333333333333333333.333333333333333333333333333333333333333333333333333333333333"`
or more long numbers, like this inverted prime number: `bigRat("3/123456789123456789123456789123456789123456821").toDecimal(65535)`

**Comment by sharkdp** [comment]
Adding true support for big integers or rationals is out of the scope for Insect. It's a *numerical* calculator with an inherent uncertainty (it "only" supports 30 digits).

See the "Pros and cons" as well as the "FAQ" sections in the README (*"Insect is a scientific calculator. It's not a computer algebra system"*)
