### ISSUE TITLE
Show possible alternative unit conversions

### ISSUE THREAD

**Issue by ZumyT** [sharkdp/insect#183]
Hi, 

Congrats on an excellent project!
I would like to suggest an idea where, on the output result, there would be an option to show derived units alongside the base one.
For example, an entry of:

>> 1 V / 1 A yields 
      = 1 V/A 

It would be very interesting that output comes in **expanded** form as for example:

>> 1 V / 1 A  
      = 1 Ohm  -> 1 V/A ->1  S^-1 -> 1 W / A^2 ->1 A^(-2) × kg × m^2 × s^(-3)

This would be very helpfull since it provides some insight into the nature of phyisical quantites.
For example, the magnetic field energy density _w_ is given in T^2 A^2 / N and when working with [Ampere force](https://en.wikipedia.org/wiki/Amp%C3%A8re%27s_force_law) on current carrying conductors it is very useful to know that T^2 A^2 / N i.e. magnetic energy density has a unit of a pressure N/m^2. 
Also, it would be nice to have a **base** command for direct conversion of desired units.
For example:

>> 1 V/A  -> base
>> V  -> base

With **expand** command

>> 1 V/A -> expand

Kind Regards, Zumy

**Comment by sharkdp** [comment]
I think this could only be solved by a giant database of "useful" units (like *N/m^2*) because I don't see a way to write a generic algorithm that would solve this problem (e.g: why is *N/m²* useful but *J/m³* not? or is it?)

**Comment by sharkdp** [comment]
> Also, it would be nice to have a **base** command for direct conversion of desired units.

Absolutely, that would be really cool to have. It was already on my personal to-do list. I would appreciate if you could open a second ticket for that.

**Comment by ZumyT** [comment]
> 
> 
> I think this could only be solved by a giant database of "useful" units (like _N/m^2_) because I don't see a way to write a generic algorithm that would solve this problem (e.g: why is _N/m²_ useful but _J/m³_ not? or is it?)

Hmm, probably you are right. The only way I can see it also is to have a large database or maybe a smaller one which would convert given units only in terms of **energy, time, force, speed, charge** and maybe some other more tangible quantity. It is to think about it :)  
For example our previous example: "T² A² / N given in force(pressure) is N/m² and in energy(density) J/m³ where both of them are useful conversions. 

> 
> 
> > Also, it would be nice to have a **base** command for direct conversion of desired units.
> 
> Absolutely, that would be really cool to have. It was already on my personal to-do list. I would appreciate if you could open a second ticket for that.

Okay, will do it. 

BRZ

**Comment by sharkdp** [comment]
Closing thi sin favor of #184
