### ISSUE TITLE
Add Astronomical unit

### ISSUE THREAD

**Issue by infinite027** [sharkdp/insect#185]
There is support for light years so i think AUs should probably get added as well.

**Comment by infinite027** [comment]
There is only "AU" that indicates an astronomical unit. I requested a change to add "au" and "Astronomical unit"

**Comment by sharkdp** [comment]
We have `AU` for astronomic unit alrey (see the list of units here: https://github.com/sharkdp/insect#reference)

> I requested a change to add "au" and "Astronomical unit"

where?
