### ISSUE TITLE
Knots and nautical miles

### ISSUE THREAD

**Issue by zaari** [sharkdp/insect#190]
Please, add support for knot and nautical mile unites. They are the units used in maritime and air navigation.

**Comment by sharkdp** [comment]
Sounds good to me.

**Comment by amportugal** [comment]
I would like to do this, if you want my help!

**Comment by sharkdp** [comment]
@amportugal Sounds great! You have to submit a PR to purescript-quantities first (my "units"-library on which Insect is based) before we can include it in Insect. There should be a few similar PRs/commits where new units have been added.

**Comment by sharkdp** [comment]
closed in #191
