### ISSUE TITLE
Build fails on TravisCI

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#193]
The `master` build is currently broken: https://travis-ci.org/sharkdp/insect/builds/524604204

It seems to fail in the browserify-stage:
```
* Browserifying...
* ERROR: Cannot read property 'call' of undefined
```

I can not reproduce the problem locally.

@n4bb12 If you find the time, it would be great if you could take a look at this (I don't know who else to ask :smile:)

**Comment by n4bb12** [comment]
taking a look, although I don't know your browserify setup at all 😢

**Comment by n4bb12** [comment]
I've tried

```
git fetch
git reset --hard origin/master
rm -rf node_modules
npm i
npm i --no-save purescript-psa
npm run build
npm test
```

Works fine. My setup:

```
npm version
{ insect: '5.0.0',
  npm: '6.9.0',
  ares: '1.15.0',
  brotli: '1.0.7',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  llhttp: '1.1.1',
  modules: '67',
  napi: '4',
  nghttp2: '1.34.0',
  node: '11.10.1',
  openssl: '1.1.1a',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.26.0',
  v8: '7.0.276.38-node.17',
  zlib: '1.2.11' }
```

From what I can see you're running your tests in latest node which is now 12.0.0, maybe this is causing your trouble.

**Comment by n4bb12** [comment]
![2019-04-26 Screenshot 001](https://user-images.githubusercontent.com/6810177/56804460-1e6cbf00-6826-11e9-88de-a0de9d10a954.png)

**Comment by n4bb12** [comment]
https://github.com/sharkdp/insect/blob/master/.travis.yml#L5
https://nodejs.org/en/download/current/
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions

**Comment by sharkdp** [comment]
Thank you very much! (see #194)
