### ISSUE TITLE
Include amp for Ampere

### ISSUE THREAD

**Issue by Carlos231** [sharkdp/insect#197]
Most commonly known abbreviation for Ampere is "amp"
Line 225 from Parser.purs
     `, Q.ampere ==> ["amperes", "ampere", "A", "amp"]`

**Comment by Carlos231** [comment]
https://github.com/sharkdp/insect/compare/master...Carlos231:patch-1

**Comment by sharkdp** [comment]
Thank you, that seems like a useful addition. We should probably also add `amps`.
