### ISSUE TITLE
not expected units

### ISSUE THREAD

**Issue by flopie2009** [sharkdp/insect#200]
With the following command: 
570 kB * 50 / 120 ms -> MB/s
The returned unit is kB/ms (which is the same as MB/s, but it is unexpected).

**Comment by sharkdp** [comment]
Thank you for reporting this!

This seems to be a general error where the conversion fails if the unit on the left is already exactly equal (in mathematical terms) to the unit on the right. I agree that this is confusing and should definitely be fixed.

**Comment by sharkdp** [comment]
The issue is fixed and the new version is online. Thank you!
