### ISSUE TITLE
Homebrew 5.2.0 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [sharkdp/insect#203]
Relates to https://github.com/Homebrew/homebrew-core/pull/41635

It seems like the 5.1.2 does not work straight like the previous 5.0.0 upgrade. The errors are tied to the missing installations of bower and pulp. 

Need some guidance on figuring out the new version upgrade.

Cheers!

**Comment by sharkdp** [comment]
Hi. The newest version of Insect (5.1.2 or the recently published 5.2.0) need to be built from source.

The following dependencies are needed during build/compile time:
- bower
- pulp
- purescript

Sorry for the inconvenience. I hope it's still possible to package Insect for Homebrew.

**Comment by chenrui333** [comment]
that is what I figured out, I dont we do have have pulp formula in homebrew core, but we do have the other two formulas. I have already update the PR to use the latest, will update further regarding the build time deps tomorrow.

**Comment by sharkdp** [comment]
For the Arch Linux package, I basically just treat it as a NPM package and let NPM install all the dependencies that are needed to compile it. Not sure if that's an option for the Homebrew package.

**Comment by chenrui333** [comment]
yeah, homebrew does the same thing of using npm to do the installation.

https://github.com/Homebrew/homebrew-core/blob/811341fbed77b0fcbf72e3beef64cc779c3b964b/Formula/insect.rb#L20-L23
```
  def install
    system "npm", "install", *Language::Node.std_npm_install_args(libexec)
    bin.install_symlink Dir["#{libexec}/bin/*"]
  end

```

**Comment by sharkdp** [comment]
ok. is there anything that we can do here, or can this ticket be closed?

**Comment by chenrui333** [comment]
@sharkdp after adding the pulp as build dependencies, it works fine now. 

Closing the issue now, thanks!!

**Comment by sharkdp** [comment]
Great, thank you very much!
