### ISSUE TITLE
AUR package: new error

### ISSUE THREAD

**Issue by matthjes** [sharkdp/insect#204]
Hi, 

Though the previous error (regarding bower) has been fixed, there is now a new error during install:

```
pulp browserify --skip-entry-point -m Insect --standalone Insect -O -t insect.js

sh: pulp: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! insect@5.1.2 browserify: `pulp browserify --skip-entry-point -m Insect --standalone Insect -O -t insect.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the insect@5.1.2 browserify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mj/.npm/_logs/2019-07-05T06_04_26_767Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! insect@5.1.2 postinstall: `bower --allow-root install && npm run browserify && npm run copy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the insect@5.1.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mj/.npm/_logs/2019-07-05T06_04_26_865Z-debug.log
==> ERROR: A failure occurred in package().
    Aborting...
Error making: insect
```

Seems like a dependency is missing.

**Comment by liara** [comment]
After installing [nodejs-pulp](https://aur.archlinux.org/packages/nodejs-pulp/) I now get `ERROR: purs executable not found.`

**Comment by sharkdp** [comment]
Sorry for the mess. I don't really know much about npm packaging and Arch packaging.

I have now updates Insect to work with the newest version of the PureScript compiler, such that we can use the system-supplied version of PureScript. I have pushed a new version to the AUR which includes bower and purescript as build dependencies. Hope this works.

**Comment by liara** [comment]
Builds fine now. Insect is a very useful tool, as are your other projects. Thank you for sharing your work.

**Comment by sharkdp** [comment]
Thank you for the feedback!
