### ISSUE TITLE
NPM archive for 5.2.0 does not contain docs

### ISSUE THREAD

**Issue by Fnux** [sharkdp/insect#207]
Hi,

The [NPM archive for insect 5.2.0](http://registry.npmjs.org/insect/-/insect-5.2.0.tgz
) does not contain the `docs/` folder. Is this intentional?

Thanks,

**Comment by sharkdp** [comment]
Fixed in 5.3.0. Thank you for reporting this.

I chose not to include the `*.md` files in `docs/`, as they are included in `README.md`.
