### ISSUE TITLE
RPM, wrong conversion

### ISSUE THREAD

**Issue by tsjordan-eng** [sharkdp/insect#210]
On the insect.sh website a conversion to RPM is not correct. I believe it is mistakenly radians per minute, rather than revolutions per minute.
```
≫ 1rpm ->deg/min
  1 rpm ➞ ° / min
   = 57.2958 °/min
≫ 360deg/min -> rpm
  360° / min ➞ rpm
   = 6.28319 rpm
≫ 1rad/min -> rpm
  1 rad / min ➞ rpm
   = 1 rpm
```

**Comment by sharkdp** [comment]
Thank you for the feedback.

This has been discussed already: see #50 and #187.

**Comment by tsjordan-eng** [comment]
Ah, I missed that. I see the logic and can agree with the justification because of the unitlessness of radians; however, I think it would be good to document it in the readme that for Hz and RPM the answers are given in radians per unit time because most people (definitely I) understand those to mean cycles per unit time. 

Great app BTW, very useful!

**Comment by sharkdp** [comment]
Yes, good idea. Let's add a section to the FAQs.
