### ISSUE TITLE
sec & csc support

### ISSUE THREAD

**Issue by reteps** [sharkdp/insect#212]
I would love this for my math classes!

**Comment by sharkdp** [comment]
Sounds good. Unfortunately, `sec` is a reserved keyword (for `second`). Apart from this, we could easily add this to `purescript-units` and (subsequently) to Insect.

**Comment by reteps** [comment]
awesome!

**Comment by sharkdp** [comment]
Note that you  also use insect to define the functions yourself:
```
secant(x)=1/cos(x)
cosecant(x)=1/sin(x)
```

**Comment by sharkdp** [comment]
> Should I add `csc` and `sec` to `Quantities` before adding them to Insect, seeing as that's where the whole bunch of trigonometric functions are?

yes, that would be great. Maybe let's directly name them `secant`/`cosecant` to avoid the clash with `sec`?

**Comment by mhmdanas** [comment]
While I can understand the rationale for doing that in Insect, I don't see a reason to not use the abbreviated names in `purescript-quantities`, because all the unit names there are spelled out fully, and it would be inconsistent with all the other abbreviated trigonometric function names in `purescript-quantities`.

Another thing, do we want to add `csc` to Insect? The clash applies only to `secant` and `second`, not `cosecant`.

**Comment by mhmdanas** [comment]
Another option popped into my mind, which is to add the full names for all trigonometric functions besides the abbreviated ones (e.g. `sine` and `cosine`), sans `sec` of course. So basically, our options now are:

- Add `csc` and `secant` only
- Add `csc`, `cosecant`, and `secant`
- Add full names for all trigonmetric functions (including `cosecant`, `csc`, and `secant`), but not `sec`

Naturally, no option is completely consistent, so which one to choose is subjective. What do you think?

**Comment by sharkdp** [comment]
Thanks for writing this up. I think I would vote for option two:

> Add `csc`, `cosecant`, and `secant`

Adding full names for all trig. functions is an interesting idea, but I have never seen someone use `cosine(…)`.

**Comment by mhmdanas** [comment]
I also think option two is the best, so I guess I'll go ahead with that unless somebody brings up a case for another option.
