### ISSUE TITLE
Why did you write such a good program in js? And not on Rust?

### ISSUE THREAD

**Issue by D1mon** [sharkdp/insect#213]
To install the program you need a bunch of dependencies (many files). And the speed is slower than in Rust! All programs did on Rust, but decided to do it on js? Why? You will not rewrite to Rust?

**Comment by sharkdp** [comment]
I don't really appreciate the presumptuous tone of these questions, but I will try to answer them anyway.

> Why did you write such a good program in js?

Thank you for the compliment (I guess). The question is wrong. Insect is not written in JavaScript. It is written in PureScript. And I think it is an excellent choice for Insect. Purescript (just like Haskell) is a superb language when it comes to writing parsers (and interpreters). I don't think there is any language that is more suited to the task. It's also a strongly typed language with a lot of compile-time guarantees, which should hopefully make Insect a more correct program overall. Something that is particularly important if you want to trust the result of mathematical calculations. PureScript *compiles* to JavaScript which enables us to easily deploy Insect on the web and as a command-line application.

> To install the program you need a bunch of dependencies (many files).

Okay. Is there an inherent problem in that?

> And the speed is slower than in Rust!

It probably is. But I don't think that speed is a defining factor for Insect.

> All programs did on Rust, but decided to do it on js?

If you had researched your questions a little bit better, you could have seen that Insect was written before all of my Rust programs. I didn't even know Rust back then. If I had, I probably would have chosen PureScript anyway for the reasons given above.

> You will not rewrite to Rust?

I really don't see any reason why I should do that. I think it's also a bit impolite to ask for such a massive endeavor when you don't even spend 2 minutes to research your questions correctly.

**Comment by D1mon** [comment]
Thanks for answers. I didn’t mean to offend you. And I had another question: Could you create executable files, that you did not have to install dependencies and collect packages. So that you can unzip and run the program. I need a version for Linux systems. Thank.

**Comment by sharkdp** [comment]
there are binaries for some versions: https://github.com/sharkdp/insect/releases/tag/v5.1.0

unfortunately, they are quite big, as they contain a JavaScript runtime.
