### ISSUE TITLE
Disabling units

### ISSUE THREAD

**Issue by EricRabil** [sharkdp/insect#214]
Hi, I am using insect's scientific calculator functionality as part of a CAS I am developing. There are some portions of the CAS which do not require units, and sometimes the unit parsing clashes with plaintext mathematics.

Is there any way for me to disable units?

**Comment by sharkdp** [comment]
Thank you for your feedback.

Units are very deeply integrated into Insect and it is currently not possible to disable them programmatically.

You could probably manually set these dictionaries to empty and get quite close: https://github.com/sharkdp/insect/blob/c94fa6481e402b2659bc0903da515478be4c0424/src/Insect/Parser.purs#L190-L293

**Comment by EricRabil** [comment]
In plain JavaScript, I was able to clear out the dictionaries before importing the main insect module, then removing the edge-case units.

```js
const parser = require('insect/output/Insect.Parser')
parser.normalUnitDict = {value0: []}
parser.imperialUnitDict = {value0: []}

const insect = require('insect/output/Insect')
// wipes out the 'd' and 't' for good measure
insect.supportedUnits = []
```

**Comment by EricRabil** [comment]
It looks like

https://github.com/sharkdp/insect/blob/f9c347c947a4f4282157931e8375e09ce2d37db3/src/Insect/Parser.purs#L297

Means that the function will still refer to the originally defined values, and can't be overwritten. Do you have any recommendations?

**Comment by sharkdp** [comment]
> Means that the function will still refer to the originally defined values, and can't be overwritten.

In PureScript, all of these units are stored in immutable data structures which are not really supposed to be modified. Modifying these from the outside, via JavaScript, is a hack that (almost) works, but it remains a hack. If you really want a version without units, I suggest that you build your own version of Insect from the PureScript sources. This way, you can manually clear the dictionaries.
