### ISSUE TITLE
Highlighting parentheses?

### ISSUE THREAD

**Issue by nchowder** [sharkdp/insect#215]
It would be really useful for me if when I type a closing parenthesis ")", the corresponding open parenthesis on the left "(" is highlighted. VS code and some other code editors have this feature. This would help me avoid mismatched parentheses.

**Comment by sharkdp** [comment]
Thank you for your feedback.

Are you talking about the webinterface or the command-line version?

It would be nice, but I'm not sure if the JS library for the terminal supports this (one the web version).

For the command-line version, I'm pretty sure that we can not support this with the current way the interactive prompt is implemented.

**Comment by nchowder** [comment]
Ok, got it. I use the cli but either one would be nice.

**Comment by sharkdp** [comment]
I'm sorry, but I'm afraid this won't happen.
