### ISSUE TITLE
Can't install without bower

### ISSUE THREAD

**Issue by lilyball** [sharkdp/insect#216]
`bower` is marked as a `devDependency` but this package has a `postinstall` script that invokes it. So if I don't have bower installed on my system and I run `npm install insect` it fails at the postinstall command.

Is the terminal install of this tool supposed to rely on bower, or is that just for the web version?

**Comment by sharkdp** [comment]
Fixed via #217 by @justinwoo :+1:

**Comment by sharkdp** [comment]
@lilyball Thank you for reporting this. Hope the fix works for you.
