### ISSUE TITLE
Allow starting a number with a decimal point

### ISSUE THREAD

**Issue by chriscraws** [sharkdp/insect#221]
`≫ 0.5` 
`= 0.5`

`≫ .5`
`Parse error at position 1: Expected identifier`

Is there possibility for supporting numbers starting with a decimal point?

**Comment by sharkdp** [comment]
It's certainly possible. The parser would have to be changed.

I'm not really sure why I decided against implementing in the past. I think I'd be in favor if someone wants to work on this.
