### ISSUE TITLE
Problem with installation on npm

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/insect#224]
Running `npm i -g insect` errors apparently because `psc-package` is not installed on my system. The error comes from this line: https://github.com/sharkdp/insect/blob/044d413827c16dcf0e22b1ac25cd97dae9850e29/package.json#L20
Shouldn't this only be used in development? If I'm missing something please correct me.

**Comment by sharkdp** [comment]
`psc-package` is needed to install the required dependencies for *building* the project. So I would think that it is correct to list it under `devDependencies`, as is currently the case:
```json
  "devDependencies": {
    "fs-extra": "^7.0.1",
    "live-server": "^1.2.1",
    "npm-run-all": "^4.1.5",
    "psc-package": "^4.0.1",
    "purescript": "^0.13.6",
    "pulp": "^13.0.0"
  }
```

Insect can not be installed without building it first.

It might easily be possible that I am misunderstanding something here. I am not very familiar with NPM.

**Comment by mhmdanas** [comment]
You're right that psc-package should be listed in `devDependencies`, but why not build insect before publishing?

**Comment by sharkdp** [comment]
Because I would think that distributing just the source would be the default way to ship NPM packages? If you prefer not to build it, you can use a package from a distribution manager or use the binaries on the release page.

**Comment by mhmdanas** [comment]
Then the dependencies needed for building from source, including psc-package, should be normal dependencies. `devDependencies` are only required for development, so NPM won't install them when running `npm i` or `npm i -g`.

**Comment by sharkdp** [comment]
Thank you for the explanation.

Maybe @justinwoo or @n4bb12 could help out here? (if you find the time)

this could be related: #180

**Comment by n4bb12** [comment]
As a rule of thumb, published packages should work out of the box. Compilations such as purescript -> js that are required to run the code should be done pre-publish.

This can still mean that you can publish the sources. Maybe the code is already written in plain JS and can be run by node as-is. Or you might publish the sources as additional files for consumption by development tools (e.g. for source or declaration maps to work).

The dependency tree can consist of quite a lot of languages and source files and it's a bit much expected from users to figure out how to build and run all of that.

A common exception is architecture-specific native code that needs to be compiled on the target system. Anything required to run this compilation needs to be a "dependency" or already be present.

The issue with `postinstall` is that it runs both when installing dependencies for local development as well as when installing the package for use as a CLI tool. This is a bit unfortunate.

Some suggested solutions:
- Run `npm i -g --ignore-scripts` to skip the `postinstall`
- Add a check for a file that only exists in development, e.g. `build.sh`. If it doesn't exist, exit immediately.
- Rename `postinstall` to something else and document that it needs to be run initially to set up the project
- Run the things in the `postinstall` script at a different stage, e.g. before `server` or before `browserify:watch`

**Comment by mhmdanas** [comment]
Thanks for the workaround @n4bb12! I'll check it out.

**Comment by JuanM04** [comment]
You shoudn't.
I, random person which runs `npm i -g insect`, shoun't run the `postinstall` script. Therefore, I shouldn't have `psc-package` installed

**Comment by n4bb12** [comment]
I don't know how insect is published, but if it says that something is missing, that would need to be fixed in insect.

**Comment by mhmdanas** [comment]
Sorry, I meant as a workaround for now, not when this issue gets fixed.

**Comment by sharkdp** [comment]
> Some suggested solutions […]

@n4bb12 Thank you very much!

The generated JS files are currently in the `.npmignore` file (`/output`, `/insect.js`). I would guess they have to be removed? Is there a way to prevent the maintainer from publishing the package without the compiled output? Or would everything be installed properly before `publish`ing?

**Comment by n4bb12** [comment]
Yea the generated files is primarily what you want to publish, so it should not be ignored from npm, only from git.

**Comment by n4bb12** [comment]
> Is there a way to prevent the maintainer from publishing the package without the compiled output?

You could do the build in a bash script and test for the existence of certain files and folders before calling `npm publish`.

```sh
if [ ! -f "$FILE" ]; then
    echo "$FILE does not exist"
fi
if [ ! -d "$DIR" ]; then
    echo "$DIR does not exist"
fi
```

something along those lines...

**Comment by n4bb12** [comment]
Or did you mean something different?

There are hooks like npm prepack that get run before doing the publish, you could use those hooks to do checks as well.

Or you pack the build step into `prepack`. There are lots of guides on that on the web 😁

**Comment by sharkdp** [comment]
@n4bb12 Thank you very much for your help.

I'm personally not going to work on this (in the next time). I've spent too much time trying to get this to work already. In the meantime, users can still install `insect` via distribution-specific packages (or install `psc-package`).

**Comment by whalehub** [comment]
@sharkdp Would it be possible to upload compiled binaries for the latest release (v5.4.0) like you did for v5.3.0?

**Comment by sharkdp** [comment]
Done. Note that there are no functional changes in the CLI version though.

**Comment by vhtkrk** [comment]
So getting this to build on Debian running under WSL was a chore. I kept running into more and more error messages during the postinstall phase. If it happens to help anyone, this is the journey I had:

First `npm i -g psc-package`

Next the insect installer complains about missing `pulp`; so `npm i -g pulp`.

After that the insect installer complained about missing `purs`, so `npm i -g purs`... but the prebuilt binary didn't work (tried to load a nonexistent `libtinfo.so.5`), and npm wanted to build PureScript from source. So I installed the Haskell stack: `curl -sSL https://get.haskellstack.org/ | sh`

Next, the `purs` installer chugged for around 10 minutes, before failing to another `libtinfo` error. At this point I installed `libtinfo5` from apt. Now trying the `npm i -g purs` again it seemed happy with the prebuilt binary, so it seems my installation of Haskell stack was unneeded. The install script finished this time, claiming `purs` was installed but I couldn't find its binary. Seems like the install script didn't place it in my `~/.npm-packages/bin` directory (where I have set my npm prefix), and I had to do it by hand:
`ln -s ~/.npm-packages/lib/node_modules/purs/node_modules/purescript/purs.bin ~/.npm-packages/bin/purs`

Now I was *finally* able to run `npm i -g insect` succesfully.

So I guess this could be simplified to:
`sudo apt install libtinfo5 && npm i -g psc-package pulp purs && ln -s ~/.npm-packages/lib/node_modules/purs/node_modules/purescript/purs.bin ~/.npm-packages/bin/purs && npm i -g insect`

**Comment by sharkdp** [comment]
> .. but all of this could be avoided by shipping the built sources from npm.

I would be in favor of this change, but I am personally tired of changing `npm` related things. I simply don't get it. If someone wants to help, it would be highly appreciated.

**Comment by n4bb12** [comment]
I don't know your past with npm and sorry for the frustration.

But npm is not a purescript registry and node doesn't execute purescript.

Like every other non-JS project published on npm you'll need a pre-publish build step or a cross-platform post-install step.

Hacktober is coming I'll try to take care of it. 😉

**Comment by sharkdp** [comment]
Thanks to the work by @n4bb12, the installation should be *much* easier now in version 5.5.0.

**Comment by mhmdanas** [comment]
@sharkdp I can indeed confirm that I was able to install Insect without any difficulties. @n4bb12 thank you for your hard work!

**Comment by whalehub** [comment]
@sharkdp Just throwing this out there, would it be possible to automate the process of creating and publishing insect binaries for new releases using something like [release-it](https://github.com/release-it/release-it)?
