### ISSUE TITLE
1 lumen does not equal 1 candela (`1 lm -> cd` returns `1 cd`)

### ISSUE THREAD

**Issue by varenc** [sharkdp/insect#225]
I haven't looked into this thoroughly at all, but insect seems to define 1 lumen as 1 candela in some cases?

```
>>> 1 lm -> cd

  1 lm ➞ cd

   = 1 cd
```

That's incorrect. It should return an error as that's an invalid conversion.

But also, this does work correctly:

```
>>> 1 lm / (1 radian)^2 -> cd

  1 lm / (1 rad)^2 ➞ cd

   = 1 cd
```

So at some level insect must know a 1 lumen = cd ⋅(angle)^2.

**Comment by varenc** [comment]
Another silly example where insect thinks 1 lm = 1 cd:

```
>>> (1 lumen ) * 1 hogshead -> cd * hogshead

  1 lm × 1 hogshead ➞ cd × hogshead

   = 1 cd·hogshead
```

But then it also does this silly unit math correctly:

```
>>> ((1 lumen ) * 1 hogshead)/(1 radian)^2 -> cd * hogshead

  1 lm × 1 hogshead / (1 rad)^2 ➞ cd × hogshead

   = 1 cd·hogshead
```

**Comment by sharkdp** [comment]
Thank you for your feedback.

> insect seems to define 1 lumen as 1 candela in some cases

It defines *1 lumen* to be *1 candela · sr* and *1 sr* (steradian) is defined as *1 m²/m²*. So

*1 lumen = 1 candela · sr = 1 candela · 1 m²/m² = 1 candela*

> That's incorrect. It should return an error as that's an invalid conversion.

I don't think so.

I see how that can be confusing if you think of *radian* and *steradian* as fundamental base units (measuring angle or solid angle). But they are not. They are [derived units](https://en.wikipedia.org/wiki/SI_derived_unit) defined as *m/m* and *m²/m²*, respectively. In a physics calculation, it is useful to explicitly write *rad* or *sr* at some places, but mathematically, these units are just placeholders for a *1*. And (solid) angles are really just dimensionless quantities.

All of the calculations you performed above are completely correct. If you want Insect to keep *rad* or *sr = rad²*, you can simply ask for it in the conversion (`5 lm -> cd · rad²`).

Note that everything also works fine if you use *degree* instead of *radian*. Insect will perform the *degree* => *radian* conversion for you:

```
>>> 400 cd * (5°)^2 -> lm

  400 cd × (5°)^2 ➞ lm

   = 3.04617 lm
```

See also:
- Entry in the [FAQs](https://github.com/sharkdp/insect#faq): *What is the relation between the units RPM, rad/s, deg/s and Hz?*
- [#50](https://github.com/sharkdp/insect/issues/50#issuecomment-288322537): *Radians per second to Hertz conversion*
- #152: *Radian-squared bug*

**Comment by sharkdp** [comment]
Any feedback?

**Comment by varenc** [comment]
Thank you for the detailed response! That was....illuminating.

What you say does make total sense now and perfectly explains why it seemed to work in some cases and not in others. So basically when I see a plain `1 cd`, the sr/rad unit is implied. (because it's not a real unit)

My only feedback is that maybe this isn't a common interpretation/convention? I lack the context to say though.  Wolfram alpha behaves the way I expect and [tells you these units are incompatible](https://www.wolframalpha.com/input/?i=1+lumen+in+candela).  If you google basic questions like "convert candela to lumen" the results are usually from flashlight forums and the answer is that you need to know the beam angle.  Insect's behavior is is unusual to me, but I'm no physicist and maybe I'm not like a typical insect user either! And thanks to your helpful response it's no longer confusing either.

Cheers!

**Comment by sharkdp** [comment]
Thank you for the feedback.

> maybe this isn't a common interpretation/convention?

That's certainly possible.

>  Wolfram alpha behaves the way I expect and [tells you these units are incompatible](https://www.wolframalpha.com/input/?i=1+lumen+in+candela).

Hm. In this example, I certainly see the appeal of Wolfram Alpha's "interpretation". User of Insect might accidentally forget to multiply by "angle squared".

However, consider this example: A trigonometric function like "tan" turns "angles into ratios". The inverse, "atan", turns "ratios into angles". Let's say I have a flashlight beam that creates a circle of radius *1* m on a wall in *10* m distance. The angle of the cone would be atan(*1* m / *10* m). In Insect, I could simply call:
```
≫ 400 cd * atan(1 m / 10 m)^2 to lm

   = 3.97354 lm≫ 400 cd * atan(1 m / 10 m)^2 to lm
```

In Wolfram Alpha, for the same query, I get ["cd (candela) and lm (lumens) are not compatible"](https://www.wolframalpha.com/input/?i=400+cd+*+atan%281+m+%2F+10+m%29%5E2+to+lm). I have to use something like
```
400 cd * atan(1 m / 10 m)^2 * rad^2 to lm

= 3.974 lm
```
to make it work.

**Comment by sharkdp** [comment]
@varenc It's been over three years, but ... there is now a completely new version of this project called [Numbat](https://github.com/sharkdp/numbat). It currently still follows Insects way of defining units — which is how the current SI standard defines those units. But Numbat is much more flexible in this respect and users can change/customize the complete unit system.

This allows us to try *alternative* proposals on how units should be defined in the SI standard. In particular, there is a [whole line of research](https://github.com/sharkdp/numbat/issues/91) which indicates that angles should *not* be treated as dimensionless. For Numbat, I wrote a version of its unit system that follows the proposal outlined in [this paper](https://arxiv.org/abs/2108.05704). You can read more about the details, advantages, and drawbacks in the PR: https://github.com/sharkdp/numbat/pull/167. But there is one advantage that directly relates to this ticket: if angles are treated as having their own base dimension, then lumen *can not be converted to* candela.

You can try out this version of Numbat here: https://numbat.dev/angles/

Things to try:
* [`1 lm -> cd`](https://numbat.dev/angles/?q=1%20lm%20-%3E%20cd) (now leads to an error, which is what you expected)
* [`1 lm / (1 radian)^2 -> cd`](https://numbat.dev/angles/?q=1+lm+%2F+%281+radian%29%5E2+-%3E+cd) (yields the expected result of `1 cd`)
* [`1 lm * (1 radian)^2 -> cd`](https://numbat.dev/angles/?q=1%20lm%20*%20(1%20radian)^2%20-%3E%20cd) (leads to an error, as it is non-sensical. note that this conversion would be allowed as per the current SI standard)

Anyway. Thought you might be interested.

> I see how that can be confusing if you think of _radian_ and _steradian_ as fundamental base units (measuring angle or solid angle). But they are not. They are [derived units](https://en.wikipedia.org/wiki/SI_derived_unit) defined as _m/m_ and _m²/m²_, respectively. In a physics calculation, it is useful to explicitly write _rad_ or _sr_ at some places, but mathematically, these units are just placeholders for a _1_. And (solid) angles are really just dimensionless quantities.

Re-reading my comment from above.. I now have a slightly different view on this topic after reading all of these papers. I'm not 100% convinced this modification should make it to the SI standard, but when dealing with units in software, it's certainly a very valuable approach.

> Wolfram alpha behaves the way I expect and [tells you these units are incompatible](https://www.wolframalpha.com/input/?i=1+lumen+in+candela).

Interestingly, that is actually not the case anymore. It currently results in `0.07958 cd` (1/4pi)?!?
