### ISSUE TITLE
Update jquery.terminal to fix shortcut bug

### ISSUE THREAD

**Issue by septatrix** [sharkdp/insect#231]
See https://github.com/jcubic/jquery.terminal/releases/tag/2.17.3 (I am referring to <kbd>CTRL</kbd>+<kbd>L</kbd>)

**Comment by sharkdp** [comment]
Sounds good - if that does not introduce any other problems.

**Comment by sharkdp** [comment]
I have updated jquery.terminal, but it does not seem to to resolve the problem

**Comment by septatrix** [comment]
Weird - it works on the jquery.terminal demo page
