### ISSUE TITLE
clipboard integration

### ISSUE THREAD

**Issue by benmaddison** [sharkdp/insect#240]
Apologies if this is already supported and I just haven't found the right documentation (I have looked).

I frequently open a calculator to do a quick sum, with the intention of inserting the result into another application - usually via the clipboard. Having to pick up a mouse to select stuff is obviously not optimal.

I can think of a couple of ways to do this:
- echo `ans` to STDOUT on exit (possibly using a different command so as not to change the behaviour of `exit`/`quit`). It appears that if an expression is provided on STDIN, this is already the behaviour.
- introduce a new command that has the effect of putting the current `ans` onto the user's clipboard.

Both the above have their uses, so I think having both would be ideal.

I have never looked at purescript before, but I'm happy attempt a PR if there's interest?

**Comment by sharkdp** [comment]
Thank you for the feedback.

> introduce a new command that has the effect of putting the current `ans` onto the user's clipboard.

That's a neat idea :+1:. I'd vote for a simple `copy` :smile: It appears you are talking about the CLI version only. Do you think there is a way we could support this in the Web version as well?

> I have never looked at purescript before, but I'm happy attempt a PR if there's interest?

I think the PureScript part would be a rather small adaptation. You could follow how `clear` or `quit` works. The actual "copy to the console" part would probably best be done in both "frontends", i.e. the CLI version (`index.js`) and the web version (`web/index.html`).

> echo `ans` to STDOUT on exit (possibly using a different command so as not to change the behaviour of `exit`/`quit`). It appears that if an expression is provided on STDIN, this is already the behaviour.

How would that help? For non-interactive cases, you can use something like `insect 3+4 | xclip` - true. But for interactive use?

> I have never looked at purescript before, but I'm happy attempt a PR if there's interest?

Sounds great!

**Comment by benmaddison** [comment]
> Thank you for the feedback.
> 
> > introduce a new command that has the effect of putting the current `ans` onto the user's clipboard.
> 
> That's a neat idea +1. I'd vote for a simple `copy` smile It appears you are talking about the CLI version only. Do you think there is a way we could support this in the Web version as well?
> 
That shouldn't be all that hard.
I've written web based "copy-to-clipboard" buttons before. Browsers block the JS call unless it is registered to a "user-action" event, hence the button in most scenarios. I'll see if it will work in this context.

> > I have never looked at purescript before, but I'm happy attempt a PR if there's interest?
> 
> I think the PureScript part would be a rather small adaptation. You could follow how `clear` or `quit` works. The actual "copy to the console" part would probably best be done in both "frontends", i.e. the CLI version (`index.js`) and the web version (`web/index.html`).
> 
Ack. I've had a quick look around at the source, and I think I see where this fits in.

> > echo `ans` to STDOUT on exit (possibly using a different command so as not to change the behaviour of `exit`/`quit`). It appears that if an expression is provided on STDIN, this is already the behaviour.
> 
> How would that help? For non-interactive cases, you can use something like `insect 3+4 | xclip` - true. But for interactive use?
> 
I was actually thinking this would be handy when you can pipe the answer straight into something else, but need to do some ad-hoc maths in the middle. E.g:
```
$ insect --echo-on-quit | thing-that-wants-a-number-that-insect-can-give-me.sh
```

> > I have never looked at purescript before, but I'm happy attempt a PR if there's interest?
> 
> Sounds great!

**Comment by sharkdp** [comment]
> I was actually thinking this would be handy when you can pipe the answer straight into something else, but need to do some ad-hoc maths in the middle. E.g:
> 
> ```
> $ insect --echo-on-quit | thing-that-wants-a-number-that-insect-can-give-me.sh
> ```

Hm.. but that would require us to show all of the other output on STDERR (in case we detect that we are not writing to an interactive terminal via `isatty`), right?

I see how that *could* be useful in some cases, but I think it's uncommon enough not to implement a new command-line option for this.

**Comment by benmaddison** [comment]
> > I was actually thinking this would be handy when you can pipe the answer straight into something else, but need to do some ad-hoc maths in the middle. E.g:
> > ```
> > $ insect --echo-on-quit | thing-that-wants-a-number-that-insect-can-give-me.sh
> > ```
> 
> Hm.. but that would require us to show all of the other output on STDERR (in case we detect that we are not writing to an interactive terminal via `isatty`), right?
> 
That's a good question.
I suppose one would need to spawn a new sub-shell for the repl with it's own tty, and then give the answer back to the caller via a tmp file or pipe. A bit like a temporary editor that `git commit ...` launches.
I have no idea how to do this in practice without some tinkering.

> I see how that _could_ be useful in some cases, but I think it's uncommon enough to not implement a new command-line option for this.

It's certainly complex enough that I won't attempt for now...
