### ISSUE TITLE
Support constant for phi

### ISSUE THREAD

**Issue by brianrodri** [sharkdp/insect#246]
My most-common use case for insect happens to be calculating column widths using `phi` (aka the [Golden ratio](https://en.wikipedia.org/wiki/Golden_ratio)).

It'd be very nice to have it defined as a global-constant, where

```purescript
phi = φ = (1 + sqrt(5)) / 2
```

**Comment by sharkdp** [comment]
Sounds great - thank you!

The only concern I have is to use `phi` as the name. `phi` is quite a common variable name for a general angle. Maybe we could simply introduce it as `golden_ratio`? It's quite a bit longer, but we have tab completion. What do you think?

**Comment by bitzl** [comment]
I just was about to open the same issue - any news on this?

Personally, I wouldn't care if it's `phi `or `golden_ratio` since there is tab completion.

Please tell me if there is anything I could do to help to add this feature.

**Comment by sharkdp** [comment]
To be honest, I do not recall why I reverted the changes in https://github.com/sharkdp/purescript-quantities/pull/40 in https://github.com/sharkdp/purescript-quantities/commit/8ee17b74ac038537f35ded48411030d74e60bc6f. Probably they caused some issues when I reactivated CI. If you want to help, you could attempt to re-open a new PR in purescript-quantities that includes the changes from https://github.com/sharkdp/purescript-quantities/pull/40.

**Comment by mhmdanas** [comment]
I've already added `phi` to `purescript-quantities` and will add it to Insect soon, but in the meanwhile you can put this in your insectrc file (https://github.com/sharkdp/insect/pull/248):

```
phi = (1 + sqrt(5)) / 2
```
