### ISSUE TITLE
Inspect functions after definition

### ISSUE THREAD

**Issue by Mstrodl** [sharkdp/insect#251]
Hi there, I often use insect's function support, but it would be nice if there were some way to inspect the value of a function after it's been defined (I want the second operation, `f` to give the same output as the first):
![image](https://user-images.githubusercontent.com/6877780/109822392-e6deb300-7c04-11eb-9243-f2f41b037365.png)

**Comment by sharkdp** [comment]
Great idea. Already working on it

**Comment by sharkdp** [comment]
Done. Ready once #252 builds successfully. Already deployed to https://insect.sh/

**Comment by Mstrodl** [comment]
@sharkdp Thanks! :)

**Comment by sharkdp** [comment]
Released in v5.7.0
