### ISSUE TITLE
Automatic simplification

### ISSUE THREAD

**Issue by smammy** [sharkdp/insect#257]
#37 described automatically simplifying units when an entire dimension could be canceled out. I would like to request that this become a little more clever. For example:

Input: `1200 W / 120 V`
Expected output: `10 A`
Actual output: `10 W/V`

If I write `1200 V A / 120 V` I get the expected result, so intuitively what I want is for insect to "realize" that watts are volt-amps and then cancel out the volts. I realize it may not be exactly that simple, but that's the idea.

I'm aware that I can write `1200 W / 120 V → A`, but that requires me to think about unit conversion upfront. ;-)

This may be related to sharkdp/purescript-quantities#27.

**Comment by sharkdp** [comment]
I agree that this would be nice. And yes, sharkdp/purescript-quantities#27 is related. Also slightly related: #184.

I'll probably not work on this anytime soon, but any help is very much appreciated.

**Comment by smammy** [comment]
Thanks, I'll play around with it if I get some free time.

**Comment by sharkdp** [comment]
The follow-up ticket for Numbat is here: https://github.com/sharkdp/numbat/issues/89

Numbat is already better than Insect w.r.t. unit simplifications. But the specific case in this ticket is not yet handled.
