### ISSUE TITLE
hours, minutes not the correct answer?

### ISSUE THREAD

**Issue by g0blin-NN** [sharkdp/insect#263]
```
> 35 min + 35 min
  35 min + 35 min
   = 70 min
```
Why is the answer not 1 hour 10 minutes?
```
> 0.35 h + 0.35 h
  0.35 h + 0.35 h
   = 0.7 h
```
= 1 h 10 min?
Do I do something wrong?
more
```
> 4.10h+0.55h+0.25h+1.45h+0.15h+0.25h+1.20h+5.20h+0.35h+0.20h+0.15h+0
.20h+1.35h+0.30h+2.20h+2.10h+0.35h+2.20h+1.20h+0.10h+1.25h+2.40h+0.50
h+1.15h+0.45h
  4.1 h + 0.55 h + 0.25 h + 1.45 h + 0.15 h + 0.25 h + 1.2 h + 5.2 h 
+ 0.35 h + 0.2 h + 0.15 h + 0.2 h + 1.35 h + 0.3 h + 2.2 h + 2.1 h + 
0.35 h + 2.2 h + 1.2 h + 0.1 h + 1.25 h + 2.4 h + 0.5 h + 1.15 h + 0.
45 h
   = 29.6 h
> 29.6 h to min
  29.6 h ➞ min
   = 1776 min
```
How to achieve a response in hours and minutes?

**Comment by mhmdanas** [comment]
> Why is the answer not 1 hour 10 minutes?

You have the mistaken assumption that each hour is split into _100_ minutes, not _60_ minutes. 35 minutes is not the same as 0.35 hours (0.35 hours is precisely 21 minutes).

> How to achieve a response in hours and minutes?

As far as I know, it's not possible in Insect to have quantities automatically displayed in multiple units, and quantities are also not automatically converted to different units. You will have to do manual division and modulo to get the response in hours and minutes, which is going to be somewhat tedious.

**Comment by creio** [comment]
https://www.timecalculator.net/

**Comment by g0blin-NN** [comment]
> You have the mistaken assumption that each hour is split into _100_ minutes, not _60_ minutes. 35 minutes is not the same as 0.35 hours (0.35 hours is precisely 21 minutes).

If I set the "h" modifier, the program should understand that we consider time. But the program does not do this. If, as you say, I am mistaken and 0.35 hours this is 21 minutes ... why does the program gives an incorrect answer?

**Comment by mhmdanas** [comment]
Sorry, I don't understand your question. The answer is completely correct. `0.35 hours (21 minutes) + 0.35 hours (21 minutes) = 0.7 hours (42 minutes)`.

**Comment by g0blin-NN** [comment]
ok. I understand. wrong.
broke the calculator
```
> 4 h 10 min + 55 min + 25 min + 1 h 45 min + 15 min + 25 min + 1 h 2
0 min + 5 h 20 min + 35 min + 20 min 15 min + 20 min + 1 h 35 min + 3
0 min + 2 h 20 min + 2 h 10 min + 35 min + 2 h 20 min + 1 h 20 min + 
10 min + 1 h 25 min + 2 h 40 min + 50 min + 1 h 15 min + 45 min
  4 h × 10 × min + 55 min + 25 min + 1 h × 45 × min + 15 min + 25 min
 + 1 h × 20 × min + 5 h × 20 × min + 35 min + 20 min × 15 × min + 20 
min + 1 h × 35 × min + 30 min + 2 h × 20 × min + 2 h × 10 × min + 35 
min + 2 h × 20 × min + 1 h × 20 × min + 10 min + 1 h × 25 × min + 2 h
 × 40 × min + 50 min + 1 h × 15 × min + 45 min
  Conversion error:
    Cannot convert unit min (base units: s)
                to unit h·min (base units: s²)
```

Insect time cannot count. simple task to fold the time

**Comment by mhmdanas** [comment]
You cannot do `4 h 10 min`, as that is implicit multiplication, i.e. `4 h * 10 min`. You have to do `4 h + 10 min`.

**Comment by g0blin-NN** [comment]
why? you see the "*" I don't.
you need to be simpler. then a modifier is needed if the program does not directly understand.

**Comment by mhmdanas** [comment]
> why? you see the "*" I don't.

Having adjacent terms be implicitly multiplied is something that's borrowed from mathematics, where you'd do something like `ab = 0` or even `(a + b)(a - b) = a^2 - b^2`, and it's exactly the mechanism by which you do `4 meter` for example (it's the same as `4 * meter`). I'd say it's a particularly elegant feature myself.

> then a modifier is needed if the program does not directly understand.

Are you proposing having a toggle that makes adjacent time quantities added? If so, I would be very opposed to it, as it would 1. increase maintenance burden, and 2. be inconsistent with the rest of the language. Or are you perhaps trying to say something else?

**Comment by sharkdp** [comment]
> > then a modifier is needed if the program does not directly understand.
> 
> Are you proposing having a toggle that makes adjacent time quantities added? If so, I would be very opposed to it, as it would 1. increase maintenance burden, and 2. be inconsistent with the rest of the language. Or are you perhaps trying to say something else?

I agree. What we  could think about would be a special new syntax for times. Something like `0:35 hours + 0:35 hours` which would result in `1:10 hours`. But I'm not sure if it's a good fit for Insect. And we would have to disallow things like `0:35 kg`.

**Comment by g0blin-NN** [comment]
простой скрипт делает больше со сложением времени, чем ваша навороченная программа. которая не понимает что от нее хотят.
![photo_2021-07-30_14-19-35](https://user-images.githubusercontent.com/66860852/127646321-9e6d8a3b-a2e0-4b51-892d-f5ec9604c0e3.jpg)

**Comment by sharkdp** [comment]
@g0blin-NN It is referred to as "implicit multiplication" in the docs. Check out this section, for example: https://github.com/sharkdp/insect#reference

In addition to what @mhmdanas said, we also want something like "15 mA hours" to be parsed as "15 * mA * hours". Values and units are (implicitly) multiplied.

**Comment by mhmdanas** [comment]
@g0blin-NN why is `2 h + 23 min` that much worse than `2 h 23 min`? I don't get it.

**Comment by g0blin-NN** [comment]
@sharkdp Maybe it's easier?
We enter the "TIME" modifier in the calculator. And then there is a calculation of time only. 4 hours 10 minutes is 4 hours 10 minutes no multiplications. After calculating, enter "END TIME". And the calculator returns to its state and continues ...

**Comment by mhmdanas** [comment]
I don't think that's a good fit for Insect. Insect does much more than adding times, and having a mode that restricts it to that doesn't sound right. I believe you would be much better served with a script like the one you wrote.

**Comment by g0blin-NN** [comment]
You did not think about why there are sections in the Calculator under Windows? could also mix everything in a bunch

**Comment by g0blin-NN** [comment]
> why is `2 h + 23 min` that much worse than `2 h 23 min`? I don't get it.

Because it is already 2 hours and 23 minutes. The rest, from the user's point of view, is superfluous. Well, it stands with a stopwatch and is the results.

**Comment by g0blin-NN** [comment]
> why is `2 h + 23 min` that much worse than `2 h 23 min`? I don't get it.

```
> 4 h + 10 min + 55 min + 25 min + 1 h + 45 min + 15 min + 25 min + 1
 h + 20 min + 5 h + 20 min + 35 min + 20 min 15 min + 20 min + 1 h + 
35 min + 30 min + 2 h + 20 min + 2 h + 10 min + 35 min + 2 h + 20 min
 + 1 h + 20 min + 10 min + 1 h + 25 min + 2 h + 40 min + 50 min + 1 h
 + 15 min + 45 min
  4 h + 10 min + 55 min + 25 min + 1 h + 45 min + 15 min + 25 min + 1
 h + 20 min + 5 h + 20 min + 35 min + 20 min × 15 × min + 20 min + 1 
h + 35 min + 30 min + 2 h + 20 min + 2 h + 10 min + 35 min + 2 h + 20
 min + 1 h + 20 min + 10 min + 1 h + 25 min + 2 h + 40 min + 50 min +
 1 h + 15 min + 45 min
  Conversion error:
    Cannot convert unit min² (base units: s²)
                to unit h (base units: s)
```
finish

**Comment by sharkdp** [comment]
I'm going to close this, as I don't see us implementing a special syntax for adding times. Let's rather leave that to dedicated tools.
