### ISSUE TITLE
subtraction rounding error

### ISSUE THREAD

**Issue by dkfz-med-phys-rad** [sharkdp/insect#265]
Subtraction and further operations seems to be wrong - that is, yields unwanted rounding - for larger numbers, e.g.
insect 100000-500.7 yields 99499.3
insect 1000000-500.7 yields 999499, however should be 999499.3

Further, I tried:
>>> pi*147²*107*2/2
  pi × 147^2 × 107 × (2 / 2)
  = 7263870
However, that ought to be 7263874.2947

**Comment by sharkdp** [comment]
please see #54
