### ISSUE TITLE
Left shift

### ISSUE THREAD

**Issue by 89z** [sharkdp/insect#278]
I tried this:

~~~
1<<29
~~~

and I got this result:

~~~
Parse error at position 2: Expected end of input
~~~

**Comment by 89z** [comment]
https://developer.mozilla.org/docs/Web/JavaScript/Reference/Operators/Left_shift

**Comment by sharkdp** [comment]
That is not supported and I am not planning on integrating bit-level operators. But a left shift is just multiplying by a power of two. So you can define
```
shift(x, n) = x * 2^n
```
and then use it as
```
> shift(1, 29)
 = 536870912
```

**Comment by 89z** [comment]
I respect your decision, but it seems a little awkward, that I can run `1<<29` in my browser console, but I cant run it in Insect? Granted, you could say the same thing about `fetch`, but I would argue that any JavaScript operator is in the same domain as this project.

**Comment by sharkdp** [comment]
Your brower console runs abitrary Javasript code, sure.

Insect is a scientific *numerical* calculator and doesn't really know about bit-wise operations. It doesn't even have the notion of an integer number. You are likely to see wrongly rounded results if the numbers get too large. It would be easy to add a new operator. But I don't want to advertize functionality that isn't 100% supported. See also: https://github.com/sharkdp/insect#pros-and-cons

**Comment by 89z** [comment]
> Insect is a scientific numerical calculator 

OK fair enough. In this context, most would agree that bitwise doesnt fit in. I respect that.
