### ISSUE TITLE
Terminal should have bottom margin

### ISSUE THREAD

**Issue by 89z** [sharkdp/insect#281]
Currently this page:

https://insect.sh

the main Terminal (`id="terminal"`) has no bottom margin at all. I tried scrolling to the bottom, and I thought the page was broken, because I couldnt get past the bottom of the terminal. Then I realized, thats not possible, because nothing is below the terminal, not even a margin.

**Comment by 89z** [comment]
https://github.com/sharkdp/insect/blob/ec7b810e0aa57736b54764ede432416a9361de22/web/main.css#L53-L55

**Comment by sharkdp** [comment]
Thank you for reporting this. Any help in fixing this would be appreciated.

**Comment by 89z** [comment]
I mean, you could just add a line like this, in the code I linked:

~~~css
margin: 2em;
~~~

**Comment by sharkdp** [comment]
Thanks.
