### ISSUE TITLE
URL based share & refreshing

### ISSUE THREAD

**Issue by ErikDeBruijn** [sharkdp/insect#282]
I'm really liking insect.sh! Great job. I did encounter a minor bug.

When I do the following, the calculation changes unexpectedly:

1. I visit insect.sh in the browser (Brave, Chromium)
2. I type 10+10 [enter], the answer is given and the URL is updated to have a query with `q=10%2B10`.
3. I refresh the page. The query is changed to `q=10+10`. This also results in the application showing a different calculation.

I made [this](https://user-images.githubusercontent.com/191236/158808158-b4a04185-c98d-4eb8-a6e9-920c05faad59.mov) screen recording of this happening.

**Comment by sharkdp** [comment]
Thank you very much for reporting this! It should be fixed (see #284)
