### ISSUE TITLE
Fedora package is dead

### ISSUE THREAD

**Issue by leoluk** [sharkdp/insect#285]
The README says there's a Fedora package, but it seems it was removed for being unmaintained: https://src.fedoraproject.org/rpms/insect/c/b63076327e9434ec97fcace91fa68eb8e91f9d57?branch=rawhide

**Comment by sharkdp** [comment]
Thank you. So I guess it can not be installed anymore? How about the "copr repository" version for older Fedora versions? I'm unsure what changes to make to the README.

**Comment by leoluk** [comment]
Both the official package and copr are dead :(

**Comment by sharkdp** [comment]
Ok, thank you.
