### ISSUE TITLE
web version: consider switching to xterm.js

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#286]
https://xtermjs.org/

**Comment by mhmdanas** [comment]
I wonder what's the motivation for doing this?

**Comment by sharkdp** [comment]
Ah, I should have added some text here. It was mostly a personal note to look into that library. The main shortcoming of the currently used library (https://terminal.jcubic.pl/) is the deep interconnection between the JS part and the CSS part. I made a lot of changes to the CSS part but had problems when I wanted to update to more recent versions as there were major conflicts in the stylesheet. And the new versions wouldn't work with my old stylesheet.

Maybe `xtermjs` has better "theming" support.

**Comment by mhmdanas** [comment]
Maybe we can look into other libraries too, just to know all available options?

**Comment by sharkdp** [comment]
> Maybe we can look into other libraries too, just to know all available options?

yes, sounds good! Just saw xtermjs by accident and "bookmarked" it here, but I haven't looked into any other options so far.

**Comment by septatrix** [comment]
Also I noticed that the current terminal is a bit broken on mobile. As soon as I enter a digit after a division it evaluates it therefore making it impossible to add any units. While this can probably be fixed with the current library, xterm.js is definitely a lot more mature and used in more projects

**Comment by sharkdp** [comment]
I think it would be great if someone interested could build a small prototype so we can evaluate if it would be a good fit for insect.

**Comment by mhmdanas** [comment]
@septatrix you're probably facing https://github.com/sharkdp/insect/issues/300.
