### ISSUE TITLE
New logo?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#294]
What does everyone think of a new logo?

![insect-banner](https://user-images.githubusercontent.com/4209276/166120334-0b67fb41-72d5-4969-bd0f-a6b2fdf9d110.svg)

There were also a few other suggestions (via a Fiverr commission), which I all discarded (and eventually went with a modified version of 2a):

1a
![logo 1](https://user-images.githubusercontent.com/4209276/166120384-3c15f08f-92cc-40d6-9c4a-14ba9c7b7387.png)

1b
![logo 2](https://user-images.githubusercontent.com/4209276/166120385-daf320ff-4d94-4361-89f4-0cade181eac8.png)

1c
![logo 3](https://user-images.githubusercontent.com/4209276/166120386-5d009fc2-dd56-4a5f-a0ec-0cb135d75ec2.png)

2a
![logo 1](https://user-images.githubusercontent.com/4209276/166120399-4380c76b-491c-4058-9a94-0a6a6b318062.png)

2b
![logo 2](https://user-images.githubusercontent.com/4209276/166120401-1e81b34e-8c10-449c-bbbf-31029fe52748.png)

2c
![logo 3](https://user-images.githubusercontent.com/4209276/166120402-d3c93dfc-9169-4390-a5bf-ce47006b277d.png)

**Comment by mhmdanas** [comment]
To be honest, I prefer the current logo over all of the ones you posted here. I don't know if I can articulate my reasons well, but the best I can come up with is that all the ones here try to be too... "modern," if you get what I mean.

**Comment by sharkdp** [comment]
Fair enough. That is why I'm asking. I don't necessarily disagree. I'll leave this ticket open for a while.

**Comment by mhmdanas** [comment]
> I'll leave this ticket open for a while.

Sure, my opinion isn't the be-all and end-all of the discussion.

**Comment by Merlin04** [comment]
I like 1c, out of all of them it seems the least "take a stock vector icon and add the text "Insect" next to it"

**Comment by Masynchin** [comment]
> To be honest, I prefer the current logo over all of the ones you posted here.

Same.

**Comment by bullbesh** [comment]
I only see the default calculator logos here. BTW, current logo is gorgeous 😈

**Comment by mhmdanas** [comment]
Looking at this again, I think I like 1c best out of all the logos in this issue. However, as stated before, I also like the current logo just fine, so maybe you can just use the same overall design but with a little more polish(?).

By the way, you haven't actually stated your own opinion yet @sharkdp. What are your thoughts?

**Comment by sharkdp** [comment]
> Looking at this again, I think I like 1c best out of all the logos in this issue. However, as stated before, I also like the current logo just fine, so maybe you can just use the same overall design but with a little more polish(?).

Totally fine with me. Glad to get some support on the current logo :smile:. I think the colors could be improved, but I actually also still like the idea itself.

Mostly out of curiosity, I also played around a bit with DALL·E last week and by *not* specifying some things, I was lead to some interesting ideas. None of this is directly logo-worthy, I believe, but maybe serves as some inspiration.

![](https://user-images.githubusercontent.com/4209276/188315049-612bb4be-ce0d-4df8-b75e-e3336f644de2.png)

![](https://user-images.githubusercontent.com/4209276/188315138-a87f7e85-2014-4b17-9022-568e4d55649c.png)

![](https://user-images.githubusercontent.com/4209276/188315142-53b746f3-d16a-4c03-94c3-67820838657c.png)

![](https://user-images.githubusercontent.com/4209276/188315146-a8d1f1fc-1536-45c1-b107-1b609021fb81.png)


![](https://user-images.githubusercontent.com/4209276/188315100-066a1603-eb7e-4a52-8e57-f82f6d7a96ac.png)

![](https://user-images.githubusercontent.com/4209276/188315104-ebae41d4-511d-4e66-a4ca-2715ca26a774.png)

![](https://user-images.githubusercontent.com/4209276/188315113-e62c227a-eaf7-4534-9300-62dc2a49a0d3.png)

![](https://user-images.githubusercontent.com/4209276/188315121-2b8c2bca-db26-4f29-9866-e1018fa7b388.png)

**Comment by Masynchin** [comment]
> I want to hear everyone's opinion here.

Let's not make a chaos here by introducing new name and new logo. Although, your idea is cool.
