### ISSUE TITLE
Insect binaries created with `nexe` bundle outdated Node.js versions

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/insect#297]
The `build.sh` script, which builds the Insect binaries published with each release among other things, creates binaries with a quite outdated Node.js version (v8.8.1). The latest Node.js that can be currently used with `nexe` without building Node.js from source (which, trust me, takes quite a while, and then imagine doing that multiple times for multiple OSs and archs!) is Node.js 14.15.3, which is also outdated (the latest Node.js version in the v14 line is v14.19.3).

Our options:
- Stop shipping pre-built binaries with each release
- Figure out how to do it by building Node.js from source (will probably take many hours for each release)
- Choose an alternative

**Comment by sharkdp** [comment]
Oh, okay. I personally don't use those binaries and only provided them for convenience. I usually try to minimize my maintenance work in terms of packaging of my application, so I am completely fine with option 1 (stop shipping pre-built binaries), unless there is a decent alternative that we can integrate easily.

**Comment by mhmdanas** [comment]
Yeah, I prefer option 1 too. My quick search didn't yield any alternatives, but it's just that, a quick search.

Shall we create a minor release (i.e. 5.8.0) without pre-built binaries to see if people will complain? If you're okay with this idea, then mind waiting until I send my PureScript 0.15.0 PR here and get it merged?

**Comment by sharkdp** [comment]
Sounds good
