### ISSUE TITLE
How to treat NaN and Infinity?

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#30]
```
> (1/0)m
Infinitym

> sqrt(-2)m
NaNm
```
:slightly_frowning_face: 

Options to deal with this:
* Add `DivideByZeroError` to `EvalError`.

**Comment by paf31** [comment]
Isn't `sqrt(-2)m` ill-typed to begin with? There is no unit `x` such that `x^2 = m`, right?

**Comment by sharkdp** [comment]
> There is no unit x such that x^2 = m, right?

There is: it is simply `x = m^0.5`. It's a perfectly fine physical unit. `sqrt` is different from most other functions (like `sin`), in that it can be applied to a dimensionful quantity.

> Edit: sorry, I parsed it wrong

no worries :smile:

**Comment by sharkdp** [comment]
Fixed by detecting numerical errors during evaluation.
