### ISSUE TITLE
Investigate and fix startup time increase

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/insect#310]
https://github.com/sharkdp/insect/pull/303 caused [a pretty bad regression in startup times](https://github.com/sharkdp/insect/pull/303#issuecomment-1145010004). We should investigate why the startup time increased and how to reduce it.

**Comment by mhmdanas** [comment]
I made `index.js` import a minified and bundled `insect.js` instead of `output/Insect/index.js`, and here are the benchmark results:

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `Startup time (insect '1+1')` | 175.9 ± 1.7 | 172.2 | 179.5 | 1.00 |

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `Startup time, stdin mode (insect < computations-1.ins)` | 194.9 ± 1.5 | 192.4 | 197.4 | 1.00 |

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `Evaluation speed (insect < computations-160.ins)` | 1114.2 ± 13.1 | 1091.9 | 1131.6 | 1.00 |

Compared to `master` and #303 (see https://github.com/sharkdp/insect/pull/303#issuecomment-1145010004), this is a HUGE improvement.

**Comment by sharkdp** [comment]
> Compared to `master` and #303 (see [#303 (comment)](https://github.com/sharkdp/insect/pull/303#issuecomment-1145010004)), this is a HUGE improvement.

Oh cool!
