### ISSUE TITLE
Trig functions that should return zero give nonzero results

### ISSUE THREAD

**Issue by jelson** [sharkdp/insect#345]
The following evaluations should all return zero. Instead, they all return values close to zero, but not zero:

sin(180 deg) returns 1.38463e-16
sin(pi), which is the same as sin(180 deg), returns 8.62803e-81
cos(pi/2) returns -2.48558e-31
cos(90 deg) returns 6.92313e-17

**Comment by sharkdp** [comment]
Insect is a numerical calculator, not a symbolic one. Even if we "patch" a few of those cases, you can never expect it to yield exact results for all possible instances (think: `sin(928792834 * pi)`).
