### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by karel-brinda** [sharkdp/insect#346]
I really like the idea of Insect and really enjoy its conversion capabilities. However, when I tried to use it for the first time as a replacement of `bc`, I got the following error:
```
/opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Data.Show/foreign.js:31
  return "\"" + s.replace(
                  ^

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at exports.showStringImpl (/opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Data.Show/foreign.js:31:19)
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Text.Parsing.Parser.String/index.js:103:106
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Control.Monad.Except.Trans/index.js:97:30
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Data.Either/index.js:206:24
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Control.Monad.State.Trans/index.js:109:34
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Data.Identity/index.js:112:20
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Control.Monad.State.Trans/index.js:108:70
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Control.Monad.State.Trans/index.js:73:24
    at /opt/homebrew/Cellar/insect/5.7.0/libexec/lib/node_modules/insect/output/Control.Monad.State.Trans/index.js:108:65

Node.js v18.11.0
```

This happened when I tried to sum up approximately 661k numbers from a file.

**Comment by mhmdanas** [comment]
I think Insect is designed to be a command-line scientific calculator, not a data processing tool, so this might be out-of-scope for Insect (or maybe not–@sharkdp could probably decide that).

**Comment by sharkdp** [comment]
Indeed. It's unfortunate, but Insect is currently probably not up to this task. But I have to ask:

1. How did you attempt to do this anyway? Construct a huge `n1+n2+…` input?
2. Note that summing many floating point numbers naively is prone to large numerical errors, see e.g. https://en.wikipedia.org/wiki/Kahan_summation_algorithm

**Comment by karel-brinda** [comment]
Thanks for you answer and also for the reference! These were just some auxiliary statistics for files (where the numerical errors didn't matter much – it was just for a quick verification that some invariants "approximately" hold), with the expression constructed by `paste -sd +`.

**Comment by sharkdp** [comment]
I see. I'm afraid we'll have to close this as "can't fix" for now. But there is a potential rewrite of Insect coming up, which will be able to solve your use case.
