### ISSUE TITLE
operator auto complete

### ISSUE THREAD

**Issue by falsified** [sharkdp/insect#347]
Any possibility of auto inserting "ans" if you enter an operator?
Been using speedcrunch forever, and this is just so much nicer and in terminal, but nothing else seems to auto insert ans. like SC.

example:  5+5 <enter>
10
type: + 5
it auto completes with: ans + 5, ready for any other operators or numbers

**Comment by sharkdp** [comment]
See #159 (originally called "Implicitly add "ans" to the begining of a command that starts with an operation")

**Comment by falsified** [comment]
Thank you sir!!
