### ISSUE TITLE
Is it possible to calculate with clock times?

### ISSUE THREAD

**Issue by vbd** [sharkdp/insect#349]
I played with the web version but didn't get it to work.

e.g. `14:30-16:02`

would be great if it returns
`92 minutes` / `1h 32 minutes`

**Comment by sharkdp** [comment]
please see #263

**Comment by sharkdp** [comment]
This is now possible in Numbat, the follow up project. You can get both answers:

[`time("16:02") - time("14:30") -> min`](https://numbat.dev/?q=time%28%2216%3A02%22%29+-+time%28%2214%3A30%22%29+-%3E+min%E2%8F%8E) results in `92 min`
[`time("16:02") - time("14:30") -> human`](https://numbat.dev/?q=time%28%2216%3A02%22%29+-+time%28%2214%3A30%22%29+-%3E+human%E2%8F%8E) results in `1 hour + 32 minutes`

**Comment by vbd** [comment]
- Used a self written golang program in the meantime.
- downloaded numbat
- tested numbat
- numbat replace my self written program

Tysm!
