### ISSUE TITLE
Save history

### ISSUE THREAD

**Issue by fdw** [sharkdp/insect#35]
I think it would be quite useful if the history (possibly including variables) can be saved and later loaded again, something akin to sessions or worksheets.

**Comment by sharkdp** [comment]
History should be saved already (in the web version). Does that work for you?

Saving variables would be an interesting addition, but I'm not sure if it should be enabled by default.

An option would be to have `save <name>` and `load <name>` commands that would save/retrieve the environment.

**Comment by fdw** [comment]
> An option would be to have save <name> and load <name> commands that would save/retrieve the environment.

This is exactly what I mean, since I rather use the commandline than the web version.

**Comment by sharkdp** [comment]
I was looking for a library on npm that would allow to write a readline REPL that supports this, but couldn't find anything. If someone has any hints on how to do this, let me know.

**Comment by fdw** [comment]
Thank you! 😃
