### ISSUE TITLE
New metric prefixes

### ISSUE THREAD

**Issue by 0xflotus** [sharkdp/insect#350]
> The [Wikipedia site of the metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix) shows new unit prefixes:
>
>| Name   | Symbol | Base 10 |
>|--------|--------|---------|
>| quetta | Q      | 1e30    |
>| ronna  | R      | 1e27    |
>| ronto  | r      | 1e-27   |
>| quecto | q      | 1e-30   |
>
>It was adopted by [BIPM](https://www.bipm.org/en/measurement-units/si-prefixes) in 2022

With **insect** I can add two datasizes like [Petabyte and Terabyte](https://insect.sh/?q=2+PB+%2B+1+TB).

> 2 PB + 1 TB
> = 2.001 PB

But it is not possible to add a Quettabyte and an Exabyte. 

Please implement the new metric prefixes to allow this.

**Comment by sharkdp** [comment]
Sounds good. Note that we have a slightly more complete set for binary prefixes. They go up to up to yobi (`YiB`):

https://github.com/sharkdp/insect/blob/75443006d910ab5680921266db917986fc12561c/src/Insect/Parser.purs#L157-L190

**Comment by 0xflotus** [comment]
> Sounds good. Note that we have a slightly more complete set for _binary_ prefixes, if you're mostly interested in data sizesa. They go up to up to yobi (`YiB`):
> 
> https://github.com/sharkdp/insect/blob/75443006d910ab5680921266db917986fc12561c/src/Insect/Parser.purs#L157-L190

Are zetta, yotta, yocto and zepto also missing? 

It's not possible to convert 1e21 m to Zm.

> 1e21 m -> Zm
> 1e+21 m ➞ Zm
> Unknown identifier: Zm

**Comment by mhmdanas** [comment]
@sharkdp do we want to have this in our next release?

**Comment by sharkdp** [comment]
I would hope it could be an easy thing to add. Unless this creates new "conflicts". Like for example, if `<new SI prefix>`+`<existing unit that takes an SI prefix>`==`<name of other existing unit>`. We wouldn't expect any such conflicts within SI, of course. But maybe with one of the non-standard units that we also support. Examples for a clash from the past: `f`(femto)+`t`(ton)==`ft`(feet).

**Comment by mhmdanas** [comment]
Hmm, I'm not motivated enough to check for conflicts at the moment, so I'm leaving it for later (or for somebody else :P), unless you want to work on it of course.

**Comment by sharkdp** [comment]
If course. I don't think we need to manually check for conflicts. I think we have parametrized tests in place that make sure that units with prefixes are properly parsed

**Comment by sadmoonphoenix** [comment]
is there any reason P and M aren't defined for peta and mega? From what I can tell, the parser is in fact case sensitive.
