### ISSUE TITLE
Calculate with Mega tons is not possible

### ISSUE THREAD

**Issue by 0xflotus** [sharkdp/insect#351]
```
> 3e6 t -> Mt
  3000000 ton ➞ Mt
  Unknown identifier: Mt
```

**Comment by mhmdanas** [comment]
You can use `Mton` or `megaton` instead.

**Comment by sharkdp** [comment]
Hm. This might be caused by this special case:

https://github.com/sharkdp/insect/blob/75443006d910ab5680921266db917986fc12561c/src/Insect/Parser.purs#L319-L321

**Comment by sharkdp** [comment]
Closing this. In Numbat, we removed `t` altogether, as it's such a useful identifier to have available (for time).
