### ISSUE TITLE
Set default units for each dimension?

### ISSUE THREAD

**Issue by tadamcz** [sharkdp/insect#353]
First of all, this is a very nice library! 

I wonder if it would be easy to add the ability to set a default unit for a dimension (on a per-session basis or globally). I didn't find another issue about this.

Suppose I want to do a bunch of calculations with lumens per area, and I want all the results to be in lumens per cm^2 for easy comparison.

By default I get this behaviour:

```
>>> 3050 lm / (1m*12mm)
  3050 lm / (1 m × 12 mm)
   = 254167 lm/m²

>>> 1521 lm / (60mm*60mm)
  1521 lm / (60 mm × 60 mm)
   = 0.4225 lm/mm²
```

I have to manually do:

```
>>> lmcm2=lm/cm^2
  lmcm2 = 1 lm/cm²

>>> 3050lm/(1m*12mm) -> lmcm2
  3050 lm / (1 m × 12 mm) ➞ lmcm2
   = 25.4167 lm/cm²

>>> 1521 lm / (60mm*60mm) -> lmcm2
  1521 lm / (60 mm × 60 mm) ➞ lmcm2
   = 42.25 lm/cm²
```

and keep typing `-> lmcm2 ` every time I want to calculate something.

It would be great to be able to define default units for a dimension, something like:

```
default lm/cm^2
``` 

Internally each dimension could be represented by its SI base unit form. Then you would have a default mapping from dimensions to units. So e.g. the dimension of "illluminance" (of which `lm/cm^2` and `lm/m^2` are units) would be represented by `candela*sr/m^2`. The mapping would map `candela*sr/m^2` to the desired `lm/cm^2` unit.

**Comment by mhmdanas** [comment]
This sounds like a nice idea, and to have the default units be persistent, you could just place them in your `.insectrc`. @sharkdp what do you think?

**Comment by sharkdp** [comment]
Thank you for your request. One (minor?) difficulty arises because the mapping between phys. dimensions and 'default units' is not a bijection. For example: energy is typically measured in units of joule and torque is typically measured in units of newton meters (mathematically the same as joule). If we have an expression in units of kg m² / s², there is no way of knowing whether it's supposed to be an energy or a torque.

**Comment by tadamcz** [comment]
Good point. In that case it doesn't seem too bad to just use one of them (as set by the user). 

Just to be clear, for any dimensions that don't have a default unit set explicitly by the user, the current behaviour would be retained.

**Comment by mhmdanas** [comment]
@sharkdp good point, that's something we should account for. A user should be able to make a conversion explicitly, which would override the default unit previously set. We should also add a facility to "unset" default units. Any syntax suggestions?

**Comment by sharkdp** [comment]
Follow up ticket in Numbat with idea on how to implement this: https://github.com/sharkdp/numbat/issues/116

See also: https://github.com/sharkdp/numbat/issues/91 / https://github.com/sharkdp/numbat/pull/167 which could potentially resolve this Energy/Torque ambiguity. But it comes at a cost...
