### ISSUE TITLE
Make the website a PWA installable app

### ISSUE THREAD

**Issue by xPaw** [sharkdp/insect#360]
https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Installable_PWAs

It requires adding a manifest file and a service worker. This would allow installing this page as a separate app both on mobile and desktop (via chrome).

A side benefit of adding a service worker also allows making it work offline.

**Comment by sharkdp** [comment]
I'd like to close this for now. In https://github.com/sharkdp/numbat, we have easier ways of installing the terminal version.
