### ISSUE TITLE
Insect errors if `xdgBasedir.data` or any of its parents don't exist

### ISSUE THREAD

**Issue by apandada1** [sharkdp/insect#364]
Cannot run insect in ARM. I get the same error message natively in `termux`, and Arch Linux ARM.

I tried two phones with `armhf` and `aarch64` architectures.

```
~ $ npm install -g insect


added 41 packages in 10s

2 packages are looking for funding
  run `npm fund` for details
npm notice
npm notice New minor version of npm available! 9.3.1 -> 9.5.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.5.1
npm notice Run npm install -g npm@9.5.1 to update!
npm notice
~ $
~ $ insect
node:fs:600
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/home/.local/share/insect-history'
    at Object.openSync (node:fs:600:3)
    at S3 (/data/data/com.termux/files/usr/lib/node_modules/insect/index.cjs:8:14840) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/data/data/com.termux/files/home/.local/share/insect-history'
}

Node.js v18.14.1
```

**Comment by apandada1** [comment]
Solution: I fixed it. Just had to create an empty file `/data/data/com.termux/files/home/.local/share/insect-history`

**Comment by sharkdp** [comment]
Thank you for reporting this. This looks indeed like a bug on our side.

**Comment by mhmdanas** [comment]
I have an Android device running Termux, so I'll handle this one.

**Comment by sharkdp** [comment]
Ah. My guess was that this isn't related to ARM/Termux at all but rather a general bug?

**Comment by mhmdanas** [comment]
@sharkdp I don't know, I can't reproduce on my x86_64 laptop at least.

**Comment by mhmdanas** [comment]
Actually, nevermind, I figured out what's happening here: this error happens if the `~/.local/share` (and presumably `~/.local` too) directory isn't present. Since I was only removing the `insect-history` file, that didn't trigger the bug. This means that that you were right, and I was wrong. :)

Anyway, with that being said, this should be a fairly simple fix. I'll send in a PR very soon.
