### ISSUE TITLE
Improve simplification of physical quantities

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#37]
An input like
```
5Mbit/s * 2h
```
should be simplified to `36 Gbit`, i.e. units of the *same dimension* should always be unified (here: `second` and `hour`). Similarly
```
5cm * 5m
```
should be simplified to either `0.25m²` or `2500cm²`

This is related to https://github.com/sharkdp/purescript-quantities/issues/16

**Comment by itdaniher** [comment]
Possibly related:

```
Welcome to insect. Type '?' if this is your first visit.
> 1 watt -> joules
Cannot unify unit 'W' with unit 'J'
> joules
1J
> watt
1W
```

compare to gnu units expansion and simplification:

```
You have: 1 watt
You want: 1 joule
conformability error
        1 kg m^2 / s^3
        1 kg m^2 / s^2
You have: 1 watt
You want:
        Definition: 1 kg m^2 / s^3
You have: 1 joule
You want:
        Definition: 1 kg m^2 / s^2

```

the latter explains this issue at hand and relates it to physical quantities, allowing a user to debug their expression. 

This is by far my favorite feature of gnu units and make-or-break for a CAS-like system that offers dimensional analysis and unit conversion.

Definitely interesting work overall, I would love to see this replace connectbot + gnu units or wolfram for basic engineering math.

Regards!

**Comment by sharkdp** [comment]
@itdaniher That's a cool feature, indeed! Thank you for the feedback... I think this is something that could be implemented rather easily.

**Comment by itdaniher** [comment]
Happy to share! I'll be keeping an eye on this project for sure.

**Comment by sharkdp** [comment]
@itdaniher This feature is now supported:

```
> 1 watt -> joules
Cannot unify unit 'W' (SI: 'm²·g/s³')
        with unit 'J' (SI: 'm²·g/s²')
> g0 * 40s + 5m
Cannot unify unit 'm' (SI: 'm')
        with unit 'm/s' (SI: 'm/s')
```

**Comment by sharkdp** [comment]
Simplification is now supported:
```
>>> 5Mbit/s * 2h

  (5Mbit / s) × 2h

   = 36000Mbit

>>> 5cm * 5m

  5cm × 5m

   = 2500cm²

>>> 120km/h * 2min

  (120km / h) × 2min

   = 4km
```
