### ISSUE TITLE
Use insectrc in non-interactive operation

### ISSUE THREAD

**Issue by sternj** [sharkdp/insect#377]
Defining a single function in `.insectrc` as:
```
logb(n,b) = log(n) / log(b)
```
and attempting to run
```bash
insect "logb(4,2)"
```

what I get is `Parse error at position 7: Expected ")"`. When I do so inside the interactive shell, I get
```
$ insect
>>> logb(4,2)

  logb(4, 2)

   = 2
```

**Comment by sharkdp** [comment]
Thank you for reporting this.
