### ISSUE TITLE
`insect` command accepts commands such as quit (both as argument and from stdin)

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/insect#381]
```console
$ insect quit # Just quits
$ insect list
List of variables:

  alpha = 0.00729735
  bohrMagneton = muB = µ_B = 9.27401e-24 J/T
  boltzmannConstant = k_B = 1.38065e-23 J/K
  c = speedOfLight = 299792458 m/s
  e = 2.71828
  electricConstant = eps0 = ε0 = 8.85419e-12 F/m
  electronCharge = elementaryCharge = 1.60218e-19 C
  electronMass = 9.10938e-31 kg
  faradayConstant = 96485.3 C/mol
  G = 6.67408e-11 m³/(s²·kg)
  g0 = gravity = 9.80665 m/s²
  goldenRatio = φ = 1.61803
  h_bar = ℏ = 1.05457e-34 J·s
  magneticConstant = mu0 = µ0 = 0.00000125664 N/A²
  N_A = avogadroConstant = 6.02214e+23 mol⁻¹
  pi = π = 3.14159
  planckConstant = 6.62607e-34 J·s
  protonMass = 1.67262e-27 kg
  R = 8.3145 J/(mol·K)
```
I'm not sure if this is something that has to be fixed, but I thought I'd point out the behavior. For things like `insect list` it might make sense, but for `insect copy`, not so much (at least currently, because Insect only accepts one line as an argument).

Also, Insect does accept such commands as stdin, though it seems to not show their output:

```console
$ printf "1\nquit\n2" | insect
1
$ printf help | insect
$ # Last command shows nothing
```

I think this isn't right, we should either show the commands' outputs, or disallow them altogether.

**Comment by sharkdp** [comment]
Thank you for reporting this.

> I think this isn't right, we should either show the commands' outputs, or disallow them altogether.

I agree
