### ISSUE TITLE
Add all SI units

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/insect#39]
- Ampere (and derived electrical units: V, C, H, F, Ω, S, Wb, T)
- Kelvin
- Mole
- Candela (and Lumen, Lux)

Other derived units
- Pascal
- Becquerel
- Gray
- Sievert

**Comment by jason-s** [comment]
FWIW if there are ambiguous interpretation or conversions I would suggest prioritizing to the primary ones. (V, A for electrical; all those others like C, H, F, ohms can be expressed in terms of the others. I've never used Wb in 20 years of being an electrical engineer; and the only time I've used T is when specifying magnetics, but never having to calculate using it.)

**Comment by sharkdp** [comment]
All of the above (and a few more) are now supported!

@jason-s I'd prefer SI units over others in all cases... Luckily, there are no ambiguous interpretations, so far (this is also checked by a pretty comprehensive test suite).
