### ISSUE TITLE
Variadic functions

### ISSUE THREAD

**Issue by garywill** [sharkdp/insect#396]
This calculator is amazing!
I was looking for some tool that allow us to easily calculate circult impedance. Frustrated until I meet Insect !

This is how we can calculate parallel two resistors:
```
 p(r1, r2) = 1 / ((1 / r1) + (1 / r2))
```
three resistors:
```
 p(r1, r2, r3) = 1 / ( (1 / r1) + (1 / r2) + (1 / r3) )
```
I'm wondering can we define a function with infinite number of arguments?

**Comment by apandada1** [comment]
How would you even supply "infinite" number of input parameters in the runtime? What are you trying to achieve?

**Comment by apandada1** [comment]
In case you are trying to use arbitrary (not infinity) number of inputs, then use a language that supports data structures (e.g. Octave/Python/Julia), instead of insect.

Then you can define an array R = [r1,r2,r3,.....].
and write a function which will return the reciprocal of the sum of reciprocals of all the elements in R.

**Comment by sharkdp** [comment]
Right now, there is only a limited set of variadic functions (with arbitrary number of arguments) in Insect: `maximum`, `minimum`, `mean`. Those are builtin functions, but there is currently no way to define variadic functions as a user.

We are currently working on a complete rewrite of Insect, and variadic functions (OR support for lists/vectors) are definitely on the roadmap — but not yet implemented.

**Comment by sharkdp** [comment]
Follow up ticket for Numbat: https://github.com/sharkdp/numbat/issues/66

**Comment by sharkdp** [comment]
@garywill This sort of thing is now fully supported in [Numbat]()

![image](https://github.com/sharkdp/insect/assets/4209276/99c50c32-0020-4c97-a762-c0c0c1a4e225)


Check the example out online here: https://numbat.dev/?q=fn+invert%28x%29+%3D+1%2Fx%E2%8F%8Efn+parallel_resistors%28resistances%29+%3D+1+%2F+sum%28map%28invert%2C+resistances%29%29%E2%8F%8Eparallel_resistors%28%5B22+k%E2%84%A6%2C+47+k%E2%84%A6%5D%29%E2%8F%8E
