### ISSUE TITLE
Neater command-line usage

### ISSUE THREAD

**Issue by jonhoo** [sharkdp/insect#40]
Currently, the CLI version is only really usable as a REPL-style interactive prompt. However, it would be really nice if it also handled the non-interactive use-case nicer.

To give an example, the *only* way to compute something like `6h -> min` currently without interactivity is currently:

```console
$ echo "6h -> min" | insect
> 6h -> min

  360min

> �
```

If you want *just* the answer, you need even more trickery:

```console
$ echo "6h -> min" | insect | grep -vE '^>' | paste -sd' ' | tr -d ' '
360min
```

And even then, it also includes color codes, and so can't directly be handled as a number (notice the `\e[36m`at the beginning, and the `\e[0m` at the end):

```console
$ echo "6h -> min" | insect | grep -vE '^>' | paste -sd' ' | tr -d ' ' | hexdump -C
00000000  1b 5b 33 36 6d 33 36 30  6d 69 6e 1b 5b 30 6d 0a  |.[36m360min.[0m.|
```

If `insect` could instead detect that it was being used in non-interactive mode, and then only output the answer (a command-line flag would also be ok), that would make this kind of use much easier. One step further would be to also add a `-e` flag to allow evaluating an expression without pipes:

```console
$ insect -e '6h -> min'
360min
```

**Comment by sharkdp** [comment]
Thank you for the feedback!

The CLI version now supports all of this:

```
> insect "6h -> min"
360min
                                                                                                      
> cat oscillation.ins 
grav = 9.81m/s²
L = 20cm
2pi*sqrt(L/grav) -> ms

> insect < oscillation.ins 
897.14ms
```

If you want an output without a unit, you could simply divide by the target unit, instead of just converting to it:
```
> insect "6h/min"
360
```

Could you check if this works for you?

**Comment by jonhoo** [comment]
@sharkdp wow, quick turnaround! it works perfectly, thanks!
