### ISSUE TITLE
The results are not accurate: `10^18 + 1 = 1000000000000000000`

### ISSUE THREAD

**Issue by phamhongphuc** [sharkdp/insect#401]
Hi, I work in blockchain programming and sometimes need a high-precision calculator to double-check results.
I felt your project was great (open-source, still being maintained, cross-platform) and decided to try using it. However, I discovered some problems that were quite serious (for me).

### 1. Calculating numbers larger than 10^18 resulted in incorrect results.

> High-precision numeric type with 30 significant digits that can handle very large (or small) exponents like 10^(10^10).

Although you say it has 30 significant digits, this is not true, calculations of numbers greater than 10^18 are always rounded.

```
> 10^18 + 1
  10^18 + 1
   = 1000000000000000000
```

```
> 1000111222333444555 + 1
  1000111222333444555 + 1
   = 1000110000000000000
```

### 2. Is there any way to show full results instead of displaying scientific notation (1e+21)?

```
> 10^20
  10^20
   = 100000000000000000000

> 10^21
  10^21
   = 1e+21
```

**Comment by sharkdp** [comment]
Thank you for the feedback. Please see #54. We currently also work on a complete rewrite of Insect, and I hope to be able to tackle this problem there.
