### ISSUE TITLE
Convert output to Standard Scientific Notation

### ISSUE THREAD

**Issue by MrMineev** [sharkdp/insect#402]
I can't find how to convert the output to scientific notation. Is there a way to do this?

I tried adding the -> 10^2 unit. However, this didn't work; here is an example of what I mean:

```
>>> Mass = 100 kg

  Mass = 100 kg

>>> Mass -> 10^2 kg

  Mass ➞ 10^2 × kg

   = 100 kg
```

I was dealing with very small values, it would be helpful to be able to output them in scientific notation.

**Comment by charlescochran** [comment]
Also wondering this.

**Comment by sharkdp** [comment]
Closing this in favor of https://github.com/sharkdp/numbat/issues/219 on the follow-up project.
