### ISSUE TITLE
Insect giving incorrect result!

### ISSUE THREAD

**Issue by charlescochran** [sharkdp/insect#403]
![image](https://github.com/sharkdp/insect/assets/77219451/c529410c-4a8a-4acf-9530-3fed2a6c2452)

Insect seems to be incorrectly reporting this simple division, whereas Ubuntu's built-in calculator tool gets it right.

This is Insect terminal version 5.9.0 (installed with npm), but the web version seems to be doing it as well.

Note this behavior:

![image](https://github.com/sharkdp/insect/assets/77219451/eb894b6f-9555-44a9-a754-76ec47d4f6c4)

Perhaps it is simply rounding the result for display? But this is alarming nonetheless!

**Comment by sharkdp** [comment]
This is just rounding when displaying the numbers. The precision is not lost. But I agree that this is unfortunate. Please see https://github.com/sharkdp/numbat/issues/179, https://github.com/sharkdp/numbat/issues/219 and https://github.com/sharkdp/insect/issues/54 for more details.
