### ISSUE TITLE
[Feature]Base-N calculation

### ISSUE THREAD

**Issue by bockring** [sharkdp/insect#405]
I need Base-N calculation on BIN(Base-2) and HEX(Base-16). I hope you to do my faver! Thanks.

**Comment by sharkdp** [comment]
In the follow-up project (https://numbat.dev/), you can do this:
```
>>> 42 -> bin

    = 0b101010    [String]

>>> 0x09 + 0xaa -> hex

    = 0xb3    [String]
```

Please report additional feature requests with the Numbat project (https://github.com/sharkdp/numbat)
