### ISSUE TITLE
Broken website

### ISSUE THREAD

**Issue by archisman-panigrahi** [sharkdp/insect#408]
https://insect.sh is now a broken link. Can we switch to a github hosted webpage, maybe something like https://sharkdp.github.io/insect ?

**Comment by sharkdp** [comment]
I removed the broken link. Do we really need an easy to reach version of Insect now that we have Numbat? Is there anything that Insect can do that Numbat can't?

**Comment by archisman-panigrahi** [comment]
Not needed. This is good enough
