### ISSUE TITLE
CLI easy exit

### ISSUE THREAD

**Issue by endowdly** [sharkdp/insect#41]
So far, interrupt (CTRL-C) seems to be the only way to exit on the cli tool? 

Maybe add a more discoverable method with a common keyword like quit or exit?

**Comment by tchajed** [comment]
I usually exit REPLs with Ctrl-D (end-of-text), which works in insect as expected. Nonetheless it is an easy feature to add an exit/quit command.

**Comment by sharkdp** [comment]
I also prefer Ctrl-D, but `exit` and `quit` should also work in the newest version (2.2.0). Could you confirm that this works for you?
Thanks!

**Comment by endowdly** [comment]
both exit and quit work well and as expected! Clear also dumps the console screen. 

Well done and thanks for the quick turnaround.
