### ISSUE TITLE
Binary operations on hex int32s

### ISSUE THREAD

**Issue by soupi** [sharkdp/insect#42]
Hi! Awesome project! Will you be willing to accept a PR adding hex ints with binary operations? (add, or, xor shr, etc.)

**Comment by sharkdp** [comment]
> Will you be willing to accept a PR adding hex ints with binary operations? (add, or, xor shr, etc.)

Great suggestion, but I'd like to think about this carefully.

The main use case of insect (for me) is scientific calculations with physical units. Therefore, it is important that additional features do not lead to any trade-offs. At the moment, I don't see any problems and I believe it could be added without any interference. However, if this would require substantial modifications to the parser, I would probably be against this... but let's try! Maybe it would be best to start with just accepting hex ints as inputs for numbers.

> Awesome project!

Thank you!

**Comment by soupi** [comment]
Ok, I will give it a shot :)

**Comment by soupi** [comment]
I have made an attempt at this and was able to parse hex numbers, but felt like what it'd like to achieve (a bit/hex calculator) is not entirely aligned with the goals of this project and i haven't found a simple way to make this work right now. Sorry.

I think I will just fork this project and change the language so it will only serve as bit/hex calculator, if that's ok with you.

**Comment by sharkdp** [comment]
> I have made an attempt at this and was able to parse hex numbers, but felt like what it'd like to achieve (a bit/hex calculator) is not entirely aligned with the goals of this project and i haven't found a simple way to make this work right now. Sorry.

Ok, let me know if that changes in the future.

> I think I will just fork this project and change the language so it will only serve as bit/hex calculator, if that's ok with you.

Of course! That's why this project is open source... and don't forget to share your progress :smile:

**Comment by soupi** [comment]
It's still a bit rough, but here it is: https://soupi.github.io/insect/

**Comment by sharkdp** [comment]
Very nice! *b*insect :smile: :+1:
