### ISSUE TITLE
Complex/imaginary numbers

### ISSUE THREAD

**Issue by vbvyas** [sharkdp/insect#47]
@sharkdp Are you planning to add support for complex/imaginary numbers. I am up for sending a PR to add that capability 😸

**Comment by sharkdp** [comment]
Sorry for the late reply.

I agree that it would be a nice feature, but support for complex numbers doesn't have a very high priority for me, to be honest. If you are up to the challenge, I'd be glad to take pull requests :+1:.

I suspect that this might need quite a lot of changes in various involved libraries. Probably, one would have to write a complex-numbers package on top of [purescript-decimals](https://github.com/sharkdp/purescript-decimals) and replace the underlying numeric type for scalar values in [purescript-quantities](https://github.com/sharkdp/purescript-quantities) from `Decimal` to `Complex`. The final change in *insect* could be as simple as adding a variable `i` for the imaginary unit in the initial environment.

**Comment by pedrogarcia** [comment]
Yep, having support for imaginary numbers arithmetic in rectangular and polar coordinates would be a very useful feature to have for me.

**Comment by chronaeon** [comment]
Agreed that this would be a useful feature. Great job on the calc!

**Comment by garywill** [comment]
Complex number support would be great for circuit impedance calculation, when there is capacitor or inductance.

Hope ~

**Comment by sharkdp** [comment]
follow-up ticket for Numbat here: https://github.com/sharkdp/numbat/issues/180
