### ISSUE TITLE
Example commands listing style on help command is confusing

### ISSUE THREAD

**Issue by carstenhag** [sharkdp/insect#48]
Hi, visited the site for the first time and used the `?` command, and because the columns are so close together it seemed like `> 2min + 30s`   somehow results in  `> 6Mbit/s * 1.5h -> Gb` which of course makes no sense.  You could increase the distance between the columns to help readability.

**Comment by sharkdp** [comment]
Oh, thanks! :smile: 

I increased it a little bit, hope this helps. Otherwise, I'll have to think about a different formatting.
