### ISSUE TITLE
The 'clear' command does not clear the screen

### ISSUE THREAD

**Issue by dineshb-qa** [sharkdp/insect#49]
**Steps to Reproduce :**
- Go to [Web version](https://shark.fish/insect/) of calculator
- Perform some operation then enter the 'clear' command
- Observe that : The 'clear' command does not clear the screen

**Expected Result**
The 'clear' command should clear the screen

**Actual Result**
The 'clear' command does not clear the screen
![clear_command_does_not_clear_screen_21mar](https://cloud.githubusercontent.com/assets/6957604/24152905/fec2ae08-0e72-11e7-9073-54f3851a789e.png)

**Comment by sharkdp** [comment]
This should be fixed now. Could you confirm that this works for you?

**Comment by dineshb-qa** [comment]
Hi @sharkdp ,
- Yes, the 'clear' command is working now on [Web version](https://shark.fish/insect/) of calculator
