### ISSUE TITLE
New units for the culinary arts

### ISSUE THREAD

**Issue by blakcap** [sharkdp/insect#64]
Your calc is great! It's basically my goto throughout the day. I'd love if I could use it for cooking & baking as well, cuz converting between metric & US systems are a PITA. Some ideas of units:
#### Units
- US cup
- Tablespoon
- Teaspoon
- Pint

Thanks!

**Comment by sharkdp** [comment]
Thank you for the suggestion!

I have added these according to the *US customary system* (as opposed to *metric* equivalents of cup, tablespoon etc.). 

The new units can be entered as:
* US cup: `cup`
* US tablespoon: `tablespoon`, `tbsp`
* US teaspoon: `teaspoon`, `tsp`
* US liquid pint: `pint`

I hope they work as expected:

![image](https://cloud.githubusercontent.com/assets/4209276/24671565/310fa154-1972-11e7-87c9-c25c2ffc3bfd.png)



> Your calc is great! It's basically my goto throughout the day.

That's great to hear. Thank you for the feedback!
