### ISSUE TITLE
Feature Request: Factorials

### ISSUE THREAD

**Issue by dustywayfarer** [sharkdp/insect#66]
This

https://en.wikipedia.org/wiki/Factorial
http://mathworld.wolfram.com/Factorial.html

**Comment by sharkdp** [comment]
Thanks for the suggestion!

This is now implemented as `!` operator:

```
>>> 0!

   = 1

>>> 10!

   = 3628800

>>> 100!

   = 9.33262e+157
```

Since this relies on the Gamma-function internally, we also have `gamma` now:

```
>>> gamma(-1.5)

   = 2.36327
```
