### ISSUE TITLE
mileage to pace 

### ISSUE THREAD

**Issue by gvoysey** [sharkdp/insect#80]
```
15 mile/hour -> minute/mile
  15 mi / h -> min / mi
  Conversion error:
    Cannot convert unit mi/h (base units: m·s⁻¹)
                to unit min/mi (base units: m⁻¹·s)
```

This would be useful for runners and others who frequently convert between speed and pace.

**Comment by sharkdp** [comment]
Thank you very much for the feedback.

The direct conversion between mileage and pace is not supported because it's not mathematically correct (you cannot add mileage and pace, for example). You have to manually invert the mileage in order for this to work:
```
≫ 1/(15mile/hour) -> minute/mile
  1 / (15 mi / h) -> min / mi
   = 4 min/mi
```
