### ISSUE TITLE
Can't enter text using Firefox on Android with the Google Keyboard

### ISSUE THREAD

**Issue by FLamparski** [sharkdp/insect#88]
See: ![screenshot](https://i.imgur.com/0QpUHFQ.png)

Keystrokes are eaten by some part of the setup. How are you acquiring keystrokes?

**Comment by sharkdp** [comment]
Thank you for the feedback. This is probably an issue related to https://github.com/jcubic/jquery.terminal

Could you try their demo (http://terminal.jcubic.pl/)?

**Comment by FLamparski** [comment]
Indeed it is, trying to type in the demo (using "foo bar baz foo bar baz...") is inconsistent at best. Closing here.

**Comment by sharkdp** [comment]
Thank you for checking
