### ISSUE TITLE
Precision of constants

### ISSUE THREAD

**Issue by ndyankov** [sharkdp/insect#89]
≫ 1/sqrt(eps0 * mu0)
  1 / sqrt(eps0 × mu0)
   = 299792000 A·m^(0.5)/(F^(0.5)·N^(0.5))

≫ c
  c
   = 299792458 m/s

Both outputs should equal to one another.

**Comment by sharkdp** [comment]
The internal precision is much higher than what you see in the output (six significant digits for the first calculation).

For example:
```
  c × sqrt(eps0 × mu0)
   = 1
```

**Comment by Rufflewind** [comment]
How do you change the displayed precision?

**Comment by sharkdp** [comment]
It's not possible, right now. We could make that configurable, though. Good suggestion. It should be tracked somewhere else, though.
