### ISSUE TITLE
Opensearch Integration

### ISSUE THREAD

**Issue by mbarkhau** [sharkdp/insect#90]
It would be nice to have http://www.opensearch.org/ integration. 

Then I can just type `ins[ect.sh]<Tab> -> sin(45 deg) <Enter>`  and have the insect.sh page loaded with the result right there.

**Comment by sharkdp** [comment]
Sounds like a good idea. Any help is very much appreciated.

**Comment by mbarkhau** [comment]
Tested with chrome, firefox, unfortunatly edge seems to require ssl for this to work, so I couldn't test that locally.
