### ISSUE TITLE
Missing Units

### ISSUE THREAD

**Issue by RickyS** [sharkdp/insect#92]
Calories, kilocalories, furlongs, fortnight.
And the default precision of pi seems to not have enough digits.
ALSO:  Great Work!!  Much praise!!

**Comment by sharkdp** [comment]
> Calories, kilocalories, furlongs, fortnight.

Thank you for the suggestions. I'm tracking it here (together with some other new units): https://github.com/sharkdp/purescript-quantities/issues/25

> And the default precision of pi seems to not have enough digits.

Default precision of pi is ~80 digits. Insects shows results with 6 significant digits only (try `pi-3.14159`).

> ALSO: Great Work!! Much praise!!

Thank you
