### ISSUE TITLE
Support for currencies

### ISSUE THREAD

**Issue by adius** [sharkdp/insect#95]
Somehow I expected this to work:

```
50 € -> $
```

**Comment by sharkdp** [comment]
That would be nice. However, it would also require a whole new concept for 'dynamic' units that can be defined during start-up. It would also add new dependencies as Insect would have to update currency exchange rates somehow, whereas right now it can be used as an offline tool (standalone HTML+JS or standalone nodejs app).

All of these things are somehow solvable, of course, but it's currently out of the scope for this project, I'm afraid.

**Comment by fenwick67** [comment]
Would it be in-scope to add `$`, `dollars` and `€` and other monetary units *without* built-in conversions?

For example...

```
price=$0.10/lb
1kg*price
```

...would return `22.0459 dollars`?

**Comment by sharkdp** [comment]
That would be possible, I guess. Interesting idea. The usability is strongly limited, of course (basically to the use case that you demonstrated).

**Comment by sharkdp** [comment]
Thinking about this again, I don't see a way to implement this cleanly (for both web and terminal versions) without making sacrifices (longer startup times, new dependencies, large restructurings of the codebase, ..).

The idea of adding "dummy" units that cannot be converted to anything is still interesting (similar things hold for `px` or `dot`), but I'm not sure I want to add all currencies as units. Restricting to `$` and `€` also seems rather arbitrary.

I'm going to close this (for now).

**Comment by Twister915** [comment]
Not to resurrect a dead issue but having "dummy" units would be great.

Expressions like:

```1 dollar per person per hour * 20 people * 30 hours```

would be fantastic

**Comment by sharkdp** [comment]
Thank you for the feedback.

I agree.

Would you mind opening a new issue for this?

**Comment by sharkdp** [comment]
> Expressions like:
> 
> 1 dollar per person per hour * 20 people * 30 hours
> 
> would be fantastic

@fenwick67 This is now supported:

```
>>> price = $ 0.10 / lb

  price = 0.1 USD/lb

>>> 1kg * price

  1 kg × price

   = 0.220459 USD
```

@Twister915 This is now supported:

```
>>> 1 dollar per person per hour * 20 people * 30 hours

  ((1 USD / person) / h) × 20 person × 30 h

   = 600 USD
```

**Comment by utdemir** [comment]
I understand why it is closed, but it still would be an extremely useful feature.

I think `insect` can follow what `units` does, have an external exchange rate input that can be updated on demand. Actually it might make sense to just implement the ability to use unit definitions from `units` utility, which would automatically add currency support (since `units` comes with `units_cur` command which updates the exchange rates), and possibly add much more units.

**Comment by sharkdp** [comment]
Thank you for your feedback.

I currently don't have the capacity to work on this and I'm still not sure if it's a good fit for insect. a possible solution has to work both in the terminal and on the web (insect.sh).
