### ISSUE TITLE
Support for others temperatures

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [sharkdp/insect#97]
Having `Celcius` and `Fahrenheit` and maybe [others](https://en.wikipedia.org/wiki/Conversion_of_units_of_temperature) would be really nice.

This might require some deep changes though, as the value needs to be shifted and scaled rather than only scaled.

**Comment by sharkdp** [comment]
Please see the description in #68 - I don't see how this can be implemented without those drawbacks.

**Comment by GeoffreyFrogeye** [comment]
My bad, I did search if this issue was already mentionned but I did not found it.

About adding : I would suggest to convert everything to Kelvin at first. [Adding two non-absolute temperatures makes no physical sense](https://physics.stackexchange.com/a/132725), except if you're calculating an average in which case it doesn't matter:
```
average(2°C, 4°C) = (2°C + 4°C) / 2 = 3°C
average(2°C, 4°C) = (275K + 277K) / 2 = 276K = 3°C
```
While someone might expect to get `19°C + 2°C = 21°C` when someone told you something like "The temperature has risen two degrees compared to yesterday (19°C)", and not `294°C = 292K + 275K = 19° + 2°C`, I don't think he might use a scientific calculator to figure that out. And even if he does, he will probably figure out what's going on (or at least figure out that there's something fishy). And if you're still not sure about the user-experience thing, maybe add a warning about the fact that adding two non-absolute temperatures might not be what the user seek for.

About multiplying : I only could find [a not really reliable source](https://rechneronline.de/temperatur/temperature.php) for that, but you might also need to convert the temperatures to Kelvin beforehand. But again, I'm not sure if this do make a physical sense, nor if someone would actually want to do that. In which case it might not be a problem if the behaviour is undefined.

Now about some better use cases. There are countless formulas where the temperature is expected in Kelvins, while most measuring devices output temperatures in degrees of some kind (this might depend on the region you live in, though). Having that feature would make the inputing of such formulas easier, and you don't have to remember the absolute zero's of any unit of temperature. And of course, I'd rather fire up insect rather than Google to convert a temperature in a unit that I understand.

And about the parsing, I guess that is the same issue to differentiate `m` (for `milli`) from `micro`, which is already correctly handled, am I right?

**Comment by sharkdp** [comment]
> My bad, I did search if this issue was already mentionned but I did not found it.

No worries. I had also trouble finding it again.. it doesn't mention the words celsius or fahrenheit :smile: 

> About adding : I would suggest to convert everything to Kelvin at first.

Then this would be the first of the (probably many) places where these temperature units would need special treatment. They are unlike all of the other units. I'm not saying it's impossible to implement this, but it would complicate things quite a lot.

> While someone might expect to get 19°C + 2°C = 21°C when someone told you something like "The temperature has risen two degrees compared to yesterday (19°C)", and not 294°C = 292K + 275K = 19° + 2°C, I don't think he might use a scientific calculator to figure that out. And even if he does, he will probably figure out what's going on (or at least figure out that there's something fishy).
> And if you're still not sure about the user-experience thing, maybe add a warning about the fact that adding two non-absolute temperatures might not be what the user seek for.

That is probably true. Good suggestion about the warning.

> About multiplying : I only could find a not really reliable source for that, but you might also need to convert the temperatures to Kelvin beforehand.

Yes, it's the same sort of ambiguity:
```
10 * 2°C ≟ 20°C
10 * 2°C ≟ 10 * 275K ≟ 2750K ≟ 2477°C
```

> But again, I'm not sure if this do make a physical sense, nor if someone would actually want to do that. In which case it might not be a problem if the behaviour is undefined.

As for temperatures in Kelvin, you absolutely want to multiply them by other quantities (as you mention below).. just think of something like the thermal energy *k_B·T*. If you don't immediately convert to Kelvin, you'll run into problems:

```
k_B × 27°C   =   1.38e-23 J/K × 27°C   ≟   (1.38e-23 × 27) J/K·°C   ≟   ??
```

at this point, you would need to convert *J/K·°C* to *J*. But what is *°C/K*? It's neither *1* nor *274*.

Here is an idea: Everything is probably safe, as you said, if you immediately convert everything to Kelvin. So what if `X °C` would be syntactic sugar for `(X + 273.15) K`? This would only allow one-way conversions, of course, but we'd probably get rid of most of the problems.

> Now about some better use cases. There are countless formulas where the temperature is expected in Kelvins, while most measuring devices output temperatures in degrees of some kind (this might depend on the region you live in, though). Having that feature would make the inputing of such formulas easier, and you don't have to remember the absolute zero's of any unit of temperature. 

(see above)

> And about the parsing, I guess that is the same issue to differentiate m (for milli) from micro, which is already correctly handled, am I right?

You are probably right, yes. Parsing should hopefully not be a problem.

**Comment by GeoffreyFrogeye** [comment]
> Here is an idea: Everything is probably safe, as you said, if you immediately convert everything to Kelvin. So what if X °C would be syntactic sugar for (X + 273.15) K?

Yes, this is a good idea (and maybe the only one). The `°C` (and others) symbol would be a special syntax for a built-in function. 

> This would only allow one-way conversions, of course, but we'd probably get rid of most of the problems.

And this is the most useful way. Also, in the case that someone tries to add degrees, having the result in Kelvins by default might help to figure out that might not be what he wants to do.

Also if you want to do the other way, for example showing the result in degrees, you might run into other problems. For example, say you have a value in `K/s`, when you do the conversion you might want the same value in `°C/s` (if a temperature rises by 1 Kelvin per second, it also rises by 1 °C per second), but if you have a value in `K` you might want the value substracted by  `273.15`. Let's not dive into that.

**Comment by sharkdp** [comment]
Just saw your "**Edit**": Concerning the `°C/s` input, that's a good point. Unfortunately, the "special syntax" idea won't solve that. The user would see the following (probably unexpected) behavior:
```
>>> 1 °C/s

  274.15 K/s

   = 274.15 K/s
```

Concerning the relative / absolute units idea.. yes, that could work. But I'm not even sure how the semantics would be. What kind of operations are allowed?

* abs+rel => probably yes
* abs+abs => probably no (but what about averages?)
* rel+rel => probably yes

**Comment by martinfrancois** [comment]
What about restricting calculations with temperatures to only those in which multiple temperature units aren't mixed and conversions are only allowed by themselves? So for example:
Allowed:
500 kJ/(kg*°C) * 1kg * 2°C = 1000 kJ
25°C to °F = 77 °F
Not allowed:
25°C + 50°F = undefined

**Comment by sharkdp** [comment]
I've decided to go with a really simple and restricted, but safe version: I added four functions `fromCelsius`, `toCelsius`, `fromFahrenheit`, `toFahrenheit`. They work like this:

* `fromCelsius` takes a **scalar value** that represents a temperature in Celsius and returns a corresponding **temperature in Kelvin**:

```
>>> fromCelsius(0)

   = 273.15 K

>>> k_B * fromCelsius(23) to meV

   = 25.5202 meV

>>> fromCelsius(23 K) # ???

  Conversion error:

    Cannot convert quantity of unit K to a scalar
```

* `toCelsius` takes a **temperature in Kelvin** and returns a **scalar value** that represents the corresponding temperature in Celsius:

```
>>> toCelsius(70 K)

   = -203.15

>>> toCelsius(25 meV / k_B)

   = 16.963

>>> toCelsius(100) # ???

  Conversion error:

    Cannot convert a scalar to a quantity of unit K
```

* `fromFahrenheit` and `toFahrenheit` work analogously.
